'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class visorLlibreriaCodiWeb_GAIA2

    '''<summary>
    '''lbldebug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldebug As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResultat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodiNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodiNode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LCWDSTIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWDSTIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIdioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdioma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LCWTPFOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWTPFOR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LCWTPFOL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWTPFOL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LCWCDTIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWCDTIP As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LCWDSTXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWDSTXT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEditarFitxer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditarFitxer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LCWDSHLP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCWDSHLP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RelacionsTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RelacionsTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RelacionsNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RelacionsNodes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RelacionsPlantillesTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RelacionsPlantillesTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RelacionsPlantillesNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RelacionsPlantillesNodes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCel As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ltCEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltCEL As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsert As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''checkedAfegirCodi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkedAfegirCodi As Global.System.Web.UI.WebControls.CheckBox
End Class
