'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmplantilla

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtCodiNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodiNode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEst As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEstBD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstBD As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtAtributs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAtributs As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''nroId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nroId As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblResultat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltTitol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltTitol As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlcanviIdioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlcanviIdioma As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lstCanviIdioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCanviIdioma As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlArbreWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlArbreWeb As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''AWEDSTIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSTIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqTitol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqTitol As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AWEDSNOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSNOM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstAWEDSSER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAWEDSSER As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rqServidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqServidor As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AWEDSROT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSROT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSDOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSDOC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSEBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSEBO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSMET As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSPEU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSPEU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSCSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSCSP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AWEDSCSI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AWEDSCSI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlPlantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlantilla As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtPLTDSTIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTDSTIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPLTDSOBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTDSOBS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkPLTSWVIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPLTSWVIS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlFullaWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFullaWeb As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''WEBDSTIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSTIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDSDES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSDES As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDSPCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSPCL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBTPBUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBTPBUS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WEBDTPUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDTPUB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDTCAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDTCAD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDSFIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSFIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDSURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBTPHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBTPHER As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WEBSWFRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBSWFRM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WEBSWEML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBSWEML As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WEBSWSSL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBSWSSL As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WEBWNMTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBWNMTH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WEBDSEBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WEBDSEBO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlNodeWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNodeWeb As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''NWEDSTIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSTIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSCAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSCAR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSEBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSEBO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSMET As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSPEU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSPEU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSCSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSCSP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NWEDSCSI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NWEDSCSI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltEst As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''pnlLCWA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLCWA As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''gaiaCodiWebTxtAbans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebTxtAbans As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gaiaCodiWebNodesAbans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebNodesAbans As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlLCW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLCW As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''gaiaCodiWebTxtDins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebTxtDins As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gaiaCodiWebNodesDins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebNodesDins As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlLCW2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLCW2 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''gaiaCodiWebTxtDespres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebTxtDespres As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gaiaCodiWebNodesDespres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaCodiWebNodesDespres As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstTipusFulla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstTipusFulla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlPltCamps1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPltCamps1 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtPLTDSNUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTDSNUM As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''pnlWebCamps1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWebCamps1 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''chkWEBDSIMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWEBDSIMP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWEBDSCND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWEBDSCND As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlPlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlt As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''pnlPltCamps2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPltCamps2 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''TextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlBootstrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBootstrap As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_642 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_642 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_637 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_637 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_648 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_648 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_636 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_636 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_630 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_630 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_653 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_653 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_638 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_638 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_633 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_633 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_655 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_655 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_632 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_632 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_650 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_650 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_673 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_673 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_649 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_649 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_652 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_652 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPLTDSNIV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPLTDSNIV As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_651 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_651 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_641 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_641 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_639 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_639 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_635 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_635 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_631 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_631 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_634 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_634 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_654 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_654 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_674 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_674 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEstilsDefinits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEstilsDefinits As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_117 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_117 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlGeneric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGeneric As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_115 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_115 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_119 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_119 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_118 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_103 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_103 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlMarges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMarges As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_28 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_25 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlCapses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCapses As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_114 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_114 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_105 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_105 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_108 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_122 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_122 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_27 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_26 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEstils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEstils As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ddlb_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_23 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_110 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_111 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_111 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_123 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_124 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_124 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlb_112 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_112 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlPltCamps3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPltCamps3 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtPLTDSAAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTDSAAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlb_PLTDSALF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlb_PLTDSALF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPLTDSALK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTDSALK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gaiaPLTCDPALTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaPLTCDPALTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gaiaPLTCDPALNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gaiaPLTCDPALNodes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCodi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltCanviCampsDb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltCanviCampsDb As Global.System.Web.UI.WebControls.Literal
End Class
