CREATE TABLE [CPDsa].[BUTLIGR2] (
    [IGRCDNOD] INT           IDENTITY (1, 1) NOT NULL,
    [IGRCDPAL] VARCHAR (50)  NOT NULL,
    [IGRINREL] INT           NOT NULL,
    [IGRINIDI] SMALLINT      NOT NULL,
    [IGRCDTIP] VARCHAR (12)  NOT NULL,
    [IGRDSPOS] VARCHAR (300) NOT NULL,
    [IGRINNOD] INT           NOT NULL,
    [IGRDSPNT] FLOAT (53)    NOT NULL,
    [IGRWSPUB] BIT           NOT NULL,
    [IGRDHFEC] DATETIME      NOT NULL,
    [IGRDSPNO] FLOAT (53)    NOT NULL,
    [IGRSWTIT] BIT           NOT NULL,
    [IGRSWVIU] BIT           NOT NULL
);

