CREATE TABLE [CPDsa].[CMTLCIF] (
    [CEMINCEM] INT           NOT NULL,
    [CEMDSCIF] CHAR (10)     NOT NULL,
    [CEMDSEMP] VARCHAR (MAX) NOT NULL,
    [CEMDSOBS] TEXT          NULL,
    CONSTRAINT [PK_CMTLCIF] PRIMARY KEY CLUSTERED ([CEMINCEM] ASC)
);

