CREATE TABLE [CPDsa].[METLATR_prova] (
    [ATRCDLTR] INT      NOT NULL,
    [ATRINCOD] INT      NOT NULL,
    [ATRTPEST] SMALLINT NOT NULL,
    [ATRTPFEC] DATETIME NOT NULL,
    [ATRDSTXT] TEXT     NOT NULL,
    [ATRDSXML] TEXT     NULL
);

