CREATE TABLE [CPDsa].[METLATR_OK] (
    [ATRCDLTR] INT            NOT NULL,
    [ATRINCOD] INT            NOT NULL,
    [ATRTPEST] SMALLINT       NOT NULL,
    [ATRTPFEC] DATETIME       NOT NULL,
    [ATRDSTXT] VARCHAR (8000) NULL,
    [ATRDSXML] VARCHAR (8000) NULL
);

