CREATE TABLE [CPDsa].[RHTLDEL] (
    [DELINCOD]  INT        IDENTITY (1, 1) NOT NULL,
    [DELDSECAP] CHAR (100) NULL,
    [DELDSEDEL] CHAR (100) NULL,
    [DELDSSUB]  TEXT       NULL,
    CONSTRAINT [PK_RHTLDEL] PRIMARY KEY CLUSTERED ([DELINCOD] ASC)
);

