CREATE TABLE [dbo].[BARRIS] (
    [BARINBAR] SMALLINT NOT NULL,
    [BARDSBAR] TEXT     NOT NULL,
    [BARINDIS] INT      NULL,
    CONSTRAINT [PK_BARRIS] PRIMARY KEY CLUSTERED ([BARINBAR] ASC) WITH (FILLFACTOR = 90)
);

