CREATE TABLE [dbo].[BLTLFOR] (
    [BLINCOD] INT           IDENTITY (1, 1) NOT NULL,
    [BLDSUSU] CHAR (10)     NULL,
    [BLDTDAT] SMALLDATETIME NULL,
    [BLDTFIN] SMALLDATETIME NULL,
    [BLCDTIP] NTEXT         NOT NULL,
    [BLCKBLO] CHAR (1)      NULL,
    [BLDSTXT] TEXT          NULL
);

