CREATE TABLE [dbo].[BUTLIAG] (
    [IAGINNOD] INT      NOT NULL,
    [IAGINIDI] SMALLINT NOT NULL,
    [IAGCDTEM] INT      NOT NULL,
    [IAGCDEQP] INT      NOT NULL,
    [IAGCDBAR] INT      NOT NULL,
    [IAGDHFEC] DATETIME NOT NULL,
    [IAGCDSIT] INT      NULL,
    [IAGDHINI] DATETIME NULL,
    [IAGDHFIN] DATETIME NULL,
    [IAGCDDIS] INT      NULL,
    CONSTRAINT [PK_BUTLIAG] PRIMARY KEY CLUSTERED ([IAGINNOD] ASC, [IAGINIDI] ASC, [IAGCDTEM] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_BUTLIAG]
    ON [dbo].[BUTLIAG]([IAGINNOD] ASC, [IAGINIDI] ASC) WITH (FILLFACTOR = 90);

