CREATE TABLE [dbo].[BUTLIGRT] (
    [IGRTCDPAL] VARCHAR (50)  NOT NULL,
    [IGRTINREL] INT           NOT NULL,
    [IGRTINIDI] SMALLINT      NOT NULL,
    [IGRTCDTIP] VARCHAR (12)  NOT NULL,
    [IGRTDSPOS] VARCHAR (300) NOT NULL,
    [IGRTINNOD] INT           NOT NULL,
    [IGRTDSPNT] FLOAT (53)    NOT NULL,
    [IGRTWSPUB] BIT           NOT NULL,
    [IGRTDHFEC] DATETIME      NOT NULL,
    [IGRTDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRTDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRT_IGRTDSPNO] DEFAULT (0) NOT NULL,
    [IGRTSWTIT] BIT           CONSTRAINT [DF_BUTLIGRT_IGRTSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRT] PRIMARY KEY CLUSTERED ([IGRTCDPAL] ASC, [IGRTINREL] ASC, [IGRTINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRT_METLIDI] FOREIGN KEY ([IGRTINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

