CREATE TABLE [dbo].[BUTLIGRB] (
    [IGRBCDPAL] VARCHAR (50)  NOT NULL,
    [IGRBINREL] INT           NOT NULL,
    [IGRBINIDI] SMALLINT      NOT NULL,
    [IGRBCDTIP] VARCHAR (12)  NOT NULL,
    [IGRBDSPOS] VARCHAR (300) NOT NULL,
    [IGRBINNOD] INT           NOT NULL,
    [IGRBDSPNT] FLOAT (53)    NOT NULL,
    [IGRBWSPUB] BIT           NOT NULL,
    [IGRBDHFEC] DATETIME      NOT NULL,
    [IGRBDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRBDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRB_IGRBDSPNO] DEFAULT (0) NOT NULL,
    [IGRBSWTIT] BIT           CONSTRAINT [DF_BUTLIGRB_IGRBSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRB] PRIMARY KEY CLUSTERED ([IGRBCDPAL] ASC, [IGRBINREL] ASC, [IGRBINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRB_METLIDI] FOREIGN KEY ([IGRBINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

