CREATE TABLE [dbo].[BUTLIGRN] (
    [IGRNCDPAL] VARCHAR (50)  NOT NULL,
    [IGRNINREL] INT           NOT NULL,
    [IGRNINIDI] SMALLINT      NOT NULL,
    [IGRNCDTIP] VARCHAR (12)  NOT NULL,
    [IGRNDSPOS] VARCHAR (300) NOT NULL,
    [IGRNINNOD] INT           NOT NULL,
    [IGRNDSPNT] FLOAT (53)    NOT NULL,
    [IGRNWSPUB] BIT           NOT NULL,
    [IGRNDHFEC] DATETIME      NOT NULL,
    [IGRNDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRNDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRN_IGRNDSPNO] DEFAULT (0) NOT NULL,
    [IGRNSWTIT] BIT           CONSTRAINT [DF_BUTLIGRN_IGRNSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRN] PRIMARY KEY CLUSTERED ([IGRNCDPAL] ASC, [IGRNINREL] ASC, [IGRNINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRN_METLIDI] FOREIGN KEY ([IGRNINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

