CREATE TABLE [dbo].[BUTLIGRL] (
    [IGRLCDPAL] VARCHAR (50)  NOT NULL,
    [IGRLINREL] INT           NOT NULL,
    [IGRLINIDI] SMALLINT      NOT NULL,
    [IGRLCDTIP] VARCHAR (12)  NOT NULL,
    [IGRLDSPOS] VARCHAR (300) NOT NULL,
    [IGRLINNOD] INT           NOT NULL,
    [IGRLDSPNT] FLOAT (53)    NOT NULL,
    [IGRLWSPUB] BIT           NOT NULL,
    [IGRLDHFEC] DATETIME      NOT NULL,
    [IGRLDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRLDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRL_IGRLDSPNO] DEFAULT (0) NOT NULL,
    [IGRLSWTIT] BIT           CONSTRAINT [DF_BUTLIGRL_IGRLSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRL] PRIMARY KEY CLUSTERED ([IGRLCDPAL] ASC, [IGRLINREL] ASC, [IGRLINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRL_METLIDI] FOREIGN KEY ([IGRLINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

