CREATE TABLE [dbo].[BUTLITR] (
    [ITRINNOD] INT      NOT NULL,
    [ITRINIDI] SMALLINT NOT NULL,
    [ITRCDTEM] INT      NOT NULL,
    [ITRDHFEC] DATETIME NOT NULL,
    [ITRCDSIT] INT      NULL,
    CONSTRAINT [PK_BUTLITR] PRIMARY KEY CLUSTERED ([ITRINNOD] ASC, [ITRINIDI] ASC, [ITRCDTEM] ASC) WITH (FILLFACTOR = 90)
);

