CREATE TABLE [dbo].[BUTLIGRO] (
    [IGROCDPAL] VARCHAR (50)  NOT NULL,
    [IGROINREL] INT           NOT NULL,
    [IGROINIDI] SMALLINT      NOT NULL,
    [IGROCDTIP] VARCHAR (12)  NOT NULL,
    [IGRODSPOS] VARCHAR (300) NOT NULL,
    [IGROINNOD] INT           NOT NULL,
    [IGRODSPNT] FLOAT (53)    NOT NULL,
    [IGROWSPUB] BIT           NOT NULL,
    [IGRODHFEC] DATETIME      NOT NULL,
    [IGRODSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRODSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRO_IGRODSPNO] DEFAULT (0) NOT NULL,
    [IGROSWTIT] BIT           CONSTRAINT [DF_BUTLIGRO_IGROSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRO] PRIMARY KEY CLUSTERED ([IGROCDPAL] ASC, [IGROINREL] ASC, [IGROINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRO_METLIDI] FOREIGN KEY ([IGROINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

