CREATE TABLE [dbo].[BUTLENQ] (
    [ENQCDCOD] INT            IDENTITY (1, 1) NOT NULL,
    [ENQCDCER] VARCHAR (128)  NOT NULL,
    [ENQINIDI] SMALLINT       NOT NULL,
    [ENQCDTRB] INT            NOT NULL,
    [ENQCDDIF] INT            NOT NULL,
    [ENQCDHAB] INT            NOT NULL,
    [ENQCDVAL] INT            NOT NULL,
    [ENQCDOBS] VARCHAR (1024) NOT NULL,
    [ENQDHFEC] DATETIME       NOT NULL,
    CONSTRAINT [PK_BUTLENQ] PRIMARY KEY CLUSTERED ([ENQCDCOD] ASC) WITH (FILLFACTOR = 90)
);

