CREATE TABLE [dbo].[BUTLBUS] (
    [BUSCDBUS] VARCHAR (256) NOT NULL,
    [BUSINIDI] SMALLINT      NOT NULL,
    [BUSCDNUM] INT           NOT NULL,
    [BUSDHFEC] DATETIME      NOT NULL,
    [BUSSWCER] SMALLINT      CONSTRAINT [DF_BUTLBUS_BUSSWCER] DEFAULT (0) NULL,
    [BUSDHFE2] DATETIME      NULL,
    [BUSDSUSR] VARCHAR (50)  NULL,
    [BUSCDTIP] VARCHAR (3)   NULL,
    CONSTRAINT [PK_BUTLBUS] PRIMARY KEY CLUSTERED ([BUSCDBUS] ASC, [BUSINIDI] ASC, [BUSDHFEC] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLBUS_METLIDI] FOREIGN KEY ([BUSINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);


GO
CREATE NONCLUSTERED INDEX [BUTLBUS_BUSDHFEC-BUSDSUSR]
    ON [dbo].[BUTLBUS]([BUSDHFEC] ASC, [BUSDSUSR] ASC)
    INCLUDE([BUSCDTIP]);

