CREATE TABLE [dbo].[BUTLBUS_historico] (
    [BUSCDBUS] VARCHAR (256) NOT NULL,
    [BUSINIDI] SMALLINT      NOT NULL,
    [BUSCDNUM] INT           NOT NULL,
    [BUSDHFEC] DATETIME      NOT NULL,
    CONSTRAINT [PK_BUTLBUS_historico] PRIMARY KEY CLUSTERED ([BUSCDBUS] ASC, [BUSINIDI] ASC) WITH (FILLFACTOR = 90)
);

