CREATE TABLE [dbo].[BUTLIGRA] (
    [IGRACDPAL] VARCHAR (50)  NOT NULL,
    [IGRAINREL] INT           NOT NULL,
    [IGRAINIDI] SMALLINT      NOT NULL,
    [IGRACDTIP] VARCHAR (12)  NOT NULL,
    [IGRADSPOS] VARCHAR (300) NOT NULL,
    [IGRAINNOD] INT           NOT NULL,
    [IGRADSPNT] FLOAT (53)    NOT NULL,
    [IGRAWSPUB] BIT           NOT NULL,
    [IGRADHFEC] DATETIME      NOT NULL,
    [IGRADSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRADSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRA_IGRADSPNO] DEFAULT (0) NOT NULL,
    [IGRASWTIT] BIT           CONSTRAINT [DF_BUTLIGRA_IGRASWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRA] PRIMARY KEY CLUSTERED ([IGRACDPAL] ASC, [IGRAINREL] ASC, [IGRAINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRA_METLIDI] FOREIGN KEY ([IGRAINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

