CREATE TABLE [dbo].[BUTLIGRV] (
    [IGRVCDPAL] VARCHAR (50)  NOT NULL,
    [IGRVINREL] INT           NOT NULL,
    [IGRVINIDI] SMALLINT      NOT NULL,
    [IGRVCDTIP] VARCHAR (12)  NOT NULL,
    [IGRVDSPOS] VARCHAR (300) NOT NULL,
    [IGRVINNOD] INT           NOT NULL,
    [IGRVDSPNT] FLOAT (53)    NOT NULL,
    [IGRVWSPUB] BIT           NOT NULL,
    [IGRVDHFEC] DATETIME      NOT NULL,
    [IGRVDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRVDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRV_IGRVDSPNO] DEFAULT (0) NOT NULL,
    [IGRVSWTIT] BIT           CONSTRAINT [DF_BUTLIGRV_IGRVSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRV] PRIMARY KEY CLUSTERED ([IGRVCDPAL] ASC, [IGRVINREL] ASC, [IGRVINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRV_METLIDI] FOREIGN KEY ([IGRVINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

