CREATE TABLE [dbo].[BUTLIDR] (
    [IDRINNOD] INT      NOT NULL,
    [IDRINIDI] SMALLINT NOT NULL,
    [IDRCDCAR] INT      NOT NULL,
    [IDRCDDIS] INT      NOT NULL,
    [IDRCDBAR] INT      NOT NULL,
    [IDRDHFEC] DATETIME NOT NULL,
    [IDRCDSIT] INT      NULL,
    [IDRCDTEM] INT      CONSTRAINT [DF_BUTLIDR_IDRCDTEM] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BUTLIDR_2] PRIMARY KEY CLUSTERED ([IDRINNOD] ASC, [IDRINIDI] ASC, [IDRCDTEM] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_BUTLIDR_7_137819603__K1_K7]
    ON [dbo].[BUTLIDR]([IDRINNOD] ASC, [IDRCDSIT] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_BUTLIDR_7_137819603__K7_K1]
    ON [dbo].[BUTLIDR]([IDRCDSIT] ASC, [IDRINNOD] ASC);

