CREATE TABLE [dbo].[BUTLINT] (
    [INTINNOD] INT      NOT NULL,
    [INTINIDI] SMALLINT NOT NULL,
    [INTDHFEC] DATETIME NOT NULL,
    [INTCDSIT] INT      NOT NULL,
    [INTDHVIS] DATETIME NOT NULL,
    CONSTRAINT [PK_BUTLINT] PRIMARY KEY CLUSTERED ([INTINNOD] ASC, [INTINIDI] ASC) WITH (FILLFACTOR = 90)
);

