CREATE TABLE [dbo].[BUTLIGRCOM] (
    [IGRCOMCDPAL] VARCHAR (50)  NOT NULL,
    [IGRCOMINREL] INT           NOT NULL,
    [IGRCOMINIDI] SMALLINT      NOT NULL,
    [IGRCOMCDTIP] VARCHAR (12)  NOT NULL,
    [IGRCOMDSPOS] VARCHAR (300) NOT NULL,
    [IGRCOMINNOD] INT           NOT NULL,
    [IGRCOMDSPNT] FLOAT (53)    NOT NULL,
    [IGRCOMWSPUB] BIT           NOT NULL,
    [IGRCOMDHFEC] DATETIME      NOT NULL,
    [IGRCOMDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRCOMDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRCOM_IGRCOMDSPNO] DEFAULT (0) NOT NULL,
    [IGRCOMSWTIT] BIT           CONSTRAINT [DF_BUTLIGRCOM_IGRCOMSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRCOM] PRIMARY KEY CLUSTERED ([IGRCOMCDPAL] ASC, [IGRCOMINREL] ASC, [IGRCOMINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRCOM_METLIDI] FOREIGN KEY ([IGRCOMINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

