CREATE TABLE [dbo].[BUTLIGRM] (
    [IGRMCDPAL] VARCHAR (50)  NOT NULL,
    [IGRMINREL] INT           NOT NULL,
    [IGRMINIDI] SMALLINT      NOT NULL,
    [IGRMCDTIP] VARCHAR (12)  NOT NULL,
    [IGRMDSPOS] VARCHAR (300) NOT NULL,
    [IGRMINNOD] INT           NOT NULL,
    [IGRMDSPNT] FLOAT (53)    NOT NULL,
    [IGRMWSPUB] BIT           NOT NULL,
    [IGRMDHFEC] DATETIME      NOT NULL,
    [IGRMDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRMDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRM_IGRMDSPNO] DEFAULT (0) NOT NULL,
    [IGRMSWTIT] BIT           CONSTRAINT [DF_BUTLIGRM_IGRMSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRM] PRIMARY KEY CLUSTERED ([IGRMCDPAL] ASC, [IGRMINREL] ASC, [IGRMINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRM_METLIDI] FOREIGN KEY ([IGRMINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

