CREATE TABLE [dbo].[BUTLIGRP] (
    [IGRPCDPAL] VARCHAR (50)  NOT NULL,
    [IGRPINREL] INT           NOT NULL,
    [IGRPINIDI] SMALLINT      NOT NULL,
    [IGRPCDTIP] VARCHAR (12)  NOT NULL,
    [IGRPDSPOS] VARCHAR (300) NOT NULL,
    [IGRPINNOD] INT           NOT NULL,
    [IGRPDSPNT] FLOAT (53)    NOT NULL,
    [IGRPWSPUB] BIT           NOT NULL,
    [IGRPDHFEC] DATETIME      NOT NULL,
    [IGRPDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRPDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRP_IGRPDSPNO] DEFAULT (0) NOT NULL,
    [IGRPSWTIT] BIT           CONSTRAINT [DF_BUTLIGRP_IGRPSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRP] PRIMARY KEY CLUSTERED ([IGRPCDPAL] ASC, [IGRPINREL] ASC, [IGRPINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRP_METLIDI] FOREIGN KEY ([IGRPINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

