CREATE TABLE [dbo].[BUTLIGRY] (
    [IGRYCDPAL] VARCHAR (50)  NOT NULL,
    [IGRYINREL] INT           NOT NULL,
    [IGRYINIDI] SMALLINT      NOT NULL,
    [IGRYCDTIP] VARCHAR (12)  NOT NULL,
    [IGRYDSPOS] VARCHAR (300) NOT NULL,
    [IGRYINNOD] INT           NOT NULL,
    [IGRYDSPNT] FLOAT (53)    NOT NULL,
    [IGRYWSPUB] BIT           NOT NULL,
    [IGRYDHFEC] DATETIME      NOT NULL,
    [IGRYDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRYDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRY_IGRYDSPNO] DEFAULT (0) NOT NULL,
    [IGRYSWTIT] BIT           CONSTRAINT [DF_BUTLIGRY_IGRYSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRY] PRIMARY KEY CLUSTERED ([IGRYCDPAL] ASC, [IGRYINREL] ASC, [IGRYINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRY_METLIDI] FOREIGN KEY ([IGRYINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

