CREATE TABLE [dbo].[BUTLIGRF] (
    [IGRFCDPAL] VARCHAR (50)  NOT NULL,
    [IGRFINREL] INT           NOT NULL,
    [IGRFINIDI] SMALLINT      NOT NULL,
    [IGRFCDTIP] VARCHAR (12)  NOT NULL,
    [IGRFDSPOS] VARCHAR (300) NOT NULL,
    [IGRFINNOD] INT           NOT NULL,
    [IGRFDSPNT] FLOAT (53)    NOT NULL,
    [IGRFWSPUB] BIT           NOT NULL,
    [IGRFDHFEC] DATETIME      NOT NULL,
    [IGRFDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRFDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRF_IGRFDSPNO] DEFAULT (0) NOT NULL,
    [IGRFSWTIT] BIT           CONSTRAINT [DF_BUTLIGRF_IGRFSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRF] PRIMARY KEY CLUSTERED ([IGRFCDPAL] ASC, [IGRFINREL] ASC, [IGRFINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRF_METLIDI] FOREIGN KEY ([IGRFINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

