CREATE TABLE [dbo].[BUTLLOG] (
    [LOGDHFEC] DATETIME NOT NULL,
    [LOGINIDI] SMALLINT NOT NULL,
    [LOGSWFIN] BIT      NOT NULL,
    [LOGDSTMP] DATETIME NOT NULL,
    [LOGDSQUE] INT      NOT NULL,
    CONSTRAINT [PK_BUTLLOG] PRIMARY KEY CLUSTERED ([LOGDHFEC] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLLOG_METLIDI] FOREIGN KEY ([LOGINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

