CREATE TABLE [dbo].[BUTLIGRH] (
    [IGRHCDPAL] VARCHAR (50)  NOT NULL,
    [IGRHINREL] INT           NOT NULL,
    [IGRHINIDI] SMALLINT      NOT NULL,
    [IGRHCDTIP] VARCHAR (12)  NOT NULL,
    [IGRHDSPOS] VARCHAR (300) NOT NULL,
    [IGRHINNOD] INT           NOT NULL,
    [IGRHDSPNT] FLOAT (53)    NOT NULL,
    [IGRHWSPUB] BIT           NOT NULL,
    [IGRHDHFEC] DATETIME      NOT NULL,
    [IGRHDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRHDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRH_IGRHDSPNO] DEFAULT (0) NOT NULL,
    [IGRHSWTIT] BIT           CONSTRAINT [DF_BUTLIGRH_IGRHSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRH] PRIMARY KEY CLUSTERED ([IGRHCDPAL] ASC, [IGRHINREL] ASC, [IGRHINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRH_METLIDI] FOREIGN KEY ([IGRHINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

