CREATE TABLE [dbo].[BUTLVIS] (
    [VISCDVIS] INT           IDENTITY (1, 1) NOT NULL,
    [VISINCOD] INT           NOT NULL,
    [VISCDNOD] INT           NOT NULL,
    [VISDSLNK] VARCHAR (300) NOT NULL,
    [VISDSDAT] DATETIME      NOT NULL,
    [VISWNCON] INT           NOT NULL,
    CONSTRAINT [PK_BUTLVIS] PRIMARY KEY CLUSTERED ([VISCDVIS] ASC) WITH (FILLFACTOR = 90)
);

