CREATE TABLE [dbo].[BUTLIGRQ] (
    [IGRQCDPAL] VARCHAR (50)  NOT NULL,
    [IGRQINREL] INT           NOT NULL,
    [IGRQINIDI] SMALLINT      NOT NULL,
    [IGRQCDTIP] VARCHAR (12)  NOT NULL,
    [IGRQDSPOS] VARCHAR (300) NOT NULL,
    [IGRQINNOD] INT           NOT NULL,
    [IGRQDSPNT] FLOAT (53)    NOT NULL,
    [IGRQWSPUB] BIT           NOT NULL,
    [IGRQDHFEC] DATETIME      NOT NULL,
    [IGRQDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRQDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRQ_IGRQDSPNO] DEFAULT (0) NOT NULL,
    [IGRQSWTIT] BIT           CONSTRAINT [DF_BUTLIGRQ_IGRQSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRQ] PRIMARY KEY CLUSTERED ([IGRQCDPAL] ASC, [IGRQINREL] ASC, [IGRQINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRQ_METLIDI] FOREIGN KEY ([IGRQINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

