CREATE TABLE [dbo].[BUTLCRW] (
    [CRWINNOD] INT      IDENTITY (1, 1) NOT NULL,
    [CRWCDTIP] CHAR (3) NOT NULL,
    [CRWDTDAT] DATETIME NOT NULL,
    [CRWWNNUM] INT      NOT NULL,
    CONSTRAINT [PK_BUTLCRW] PRIMARY KEY CLUSTERED ([CRWINNOD] ASC)
);

