CREATE TABLE [dbo].[BUTLIGRJ] (
    [IGRJCDPAL] VARCHAR (50)  NOT NULL,
    [IGRJINREL] INT           NOT NULL,
    [IGRJINIDI] SMALLINT      NOT NULL,
    [IGRJCDTIP] VARCHAR (12)  NOT NULL,
    [IGRJDSPOS] VARCHAR (300) NOT NULL,
    [IGRJINNOD] INT           NOT NULL,
    [IGRJDSPNT] FLOAT (53)    NOT NULL,
    [IGRJWSPUB] BIT           NOT NULL,
    [IGRJDHFEC] DATETIME      NOT NULL,
    [IGRJDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRJDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRJ_IGRJDSPNO] DEFAULT (0) NOT NULL,
    [IGRJSWTIT] BIT           CONSTRAINT [DF_BUTLIGRJ_IGRJSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRJ] PRIMARY KEY CLUSTERED ([IGRJCDPAL] ASC, [IGRJINREL] ASC, [IGRJINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRJ_METLIDI] FOREIGN KEY ([IGRJINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

