CREATE TABLE [dbo].[BUTLIGRG] (
    [IGRGCDPAL] VARCHAR (50)  NOT NULL,
    [IGRGINREL] INT           NOT NULL,
    [IGRGINIDI] SMALLINT      NOT NULL,
    [IGRGCDTIP] VARCHAR (12)  NOT NULL,
    [IGRGDSPOS] VARCHAR (300) NOT NULL,
    [IGRGINNOD] INT           NOT NULL,
    [IGRGDSPNT] FLOAT (53)    NOT NULL,
    [IGRGWSPUB] BIT           NOT NULL,
    [IGRGDHFEC] DATETIME      NOT NULL,
    [IGRGDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRGDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRG_IGRGDSPNO] DEFAULT (0) NOT NULL,
    [IGRGSWTIT] BIT           CONSTRAINT [DF_BUTLIGRG_IGRGSWTIT] DEFAULT (0) NOT NULL,
    [IGRSWESB]  BIT           CONSTRAINT [DF_BUTLIGRG_IGRSWESB] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BUTLIGRG] PRIMARY KEY CLUSTERED ([IGRGCDPAL] ASC, [IGRGINREL] ASC, [IGRGINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRG_METLIDI] FOREIGN KEY ([IGRGINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Marcat per a esborrar mentre es fa la indexació', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'BUTLIGRG', @level2type = N'COLUMN', @level2name = N'IGRSWESB';

