CREATE TABLE [dbo].[BUTLIGRK] (
    [IGRKCDPAL] VARCHAR (50)  NOT NULL,
    [IGRKINREL] INT           NOT NULL,
    [IGRKINIDI] SMALLINT      NOT NULL,
    [IGRKCDTIP] VARCHAR (12)  NOT NULL,
    [IGRKDSPOS] VARCHAR (300) NOT NULL,
    [IGRKINNOD] INT           NOT NULL,
    [IGRKDSPNT] FLOAT (53)    NOT NULL,
    [IGRKWSPUB] BIT           NOT NULL,
    [IGRKDHFEC] DATETIME      NOT NULL,
    [IGRKDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRKDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRK_IGRKDSPNO] DEFAULT (0) NOT NULL,
    [IGRKSWTIT] BIT           CONSTRAINT [DF_BUTLIGRK_IGRKSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRK] PRIMARY KEY CLUSTERED ([IGRKCDPAL] ASC, [IGRKINREL] ASC, [IGRKINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRK_METLIDI] FOREIGN KEY ([IGRKINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

