CREATE TABLE [dbo].[BUTLIGRD] (
    [IGRDCDPAL] VARCHAR (50)  NOT NULL,
    [IGRDINREL] INT           NOT NULL,
    [IGRDINIDI] SMALLINT      NOT NULL,
    [IGRDCDTIP] VARCHAR (12)  NOT NULL,
    [IGRDDSPOS] VARCHAR (300) NOT NULL,
    [IGRDINNOD] INT           NOT NULL,
    [IGRDDSPNT] FLOAT (53)    NOT NULL,
    [IGRDWSPUB] BIT           NOT NULL,
    [IGRDDHFEC] DATETIME      NOT NULL,
    [IGRDDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRDDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRD_IGRDDSPNO] DEFAULT (0) NOT NULL,
    [IGRDSWTIT] BIT           CONSTRAINT [DF_BUTLIGRD_IGRDSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRD] PRIMARY KEY CLUSTERED ([IGRDCDPAL] ASC, [IGRDINREL] ASC, [IGRDINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRD_METLIDI] FOREIGN KEY ([IGRDINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

