CREATE TABLE [dbo].[BUTLIGRS] (
    [IGRSCDPAL] VARCHAR (50)  NOT NULL,
    [IGRSINREL] INT           NOT NULL,
    [IGRSINIDI] SMALLINT      NOT NULL,
    [IGRSCDTIP] VARCHAR (12)  NOT NULL,
    [IGRSDSPOS] VARCHAR (300) NOT NULL,
    [IGRSINNOD] INT           NOT NULL,
    [IGRSDSPNT] FLOAT (53)    NOT NULL,
    [IGRSWSPUB] BIT           NOT NULL,
    [IGRSDHFEC] DATETIME      NOT NULL,
    [IGRSDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRSDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRS_IGRSDSPNO] DEFAULT (0) NOT NULL,
    [IGRSSWTIT] BIT           CONSTRAINT [DF_BUTLIGRS_IGRSSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRS] PRIMARY KEY CLUSTERED ([IGRSCDPAL] ASC, [IGRSINREL] ASC, [IGRSINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRS_METLIDI] FOREIGN KEY ([IGRSINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

