CREATE TABLE [dbo].[BUTLIGRR] (
    [IGRRCDPAL] VARCHAR (50)  NOT NULL,
    [IGRRINREL] INT           NOT NULL,
    [IGRRINIDI] SMALLINT      NOT NULL,
    [IGRRCDTIP] VARCHAR (12)  NOT NULL,
    [IGRRDSPOS] VARCHAR (300) NOT NULL,
    [IGRRINNOD] INT           NOT NULL,
    [IGRRDSPNT] FLOAT (53)    NOT NULL,
    [IGRRWSPUB] BIT           NOT NULL,
    [IGRRDHFEC] DATETIME      NOT NULL,
    [IGRRDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRRDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRR_IGRRDSPNO] DEFAULT (0) NOT NULL,
    [IGRRSWTIT] BIT           CONSTRAINT [DF_BUTLIGRR_IGRRSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRR] PRIMARY KEY CLUSTERED ([IGRRCDPAL] ASC, [IGRRINREL] ASC, [IGRRINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRR_METLIDI] FOREIGN KEY ([IGRRINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

