CREATE TABLE [dbo].[BUTLIGRZ] (
    [IGRZCDPAL] VARCHAR (50)  NOT NULL,
    [IGRZINREL] INT           NOT NULL,
    [IGRZINIDI] SMALLINT      NOT NULL,
    [IGRZCDTIP] VARCHAR (12)  NOT NULL,
    [IGRZDSPOS] VARCHAR (300) NOT NULL,
    [IGRZINNOD] INT           NOT NULL,
    [IGRZDSPNT] FLOAT (53)    NOT NULL,
    [IGRZWSPUB] BIT           NOT NULL,
    [IGRZDHFEC] DATETIME      NOT NULL,
    [IGRZDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRZDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRZ_IGRZDSPNO] DEFAULT (0) NOT NULL,
    [IGRZSWTIT] BIT           CONSTRAINT [DF_BUTLIGRZ_IGRZSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRZ] PRIMARY KEY CLUSTERED ([IGRZCDPAL] ASC, [IGRZINREL] ASC, [IGRZINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRZ_METLIDI] FOREIGN KEY ([IGRZINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

