CREATE TABLE [dbo].[BUTLTMP] (
    [TMPINIDE] INT           IDENTITY (1, 1) NOT NULL,
    [TMPDSBUS] VARCHAR (256) NOT NULL,
    [TMPDTFEC] DATETIME      NOT NULL,
    [TMPDSPAS] VARCHAR (20)  NOT NULL
);

