CREATE TABLE [dbo].[BUTLIGRW] (
    [IGRWCDPAL] VARCHAR (50)  NOT NULL,
    [IGRWINREL] INT           NOT NULL,
    [IGRWINIDI] SMALLINT      NOT NULL,
    [IGRWCDTIP] VARCHAR (12)  NOT NULL,
    [IGRWDSPOS] VARCHAR (300) NOT NULL,
    [IGRWINNOD] INT           NOT NULL,
    [IGRWDSPNT] FLOAT (53)    NOT NULL,
    [IGRWWSPUB] BIT           NOT NULL,
    [IGRWDHFEC] DATETIME      NOT NULL,
    [IGRWDSFTI] INT           IDENTITY (1, 1) NOT NULL,
    [IGRWDSPNO] FLOAT (53)    CONSTRAINT [DF_BUTLIGRW_IGRWDSPNO] DEFAULT (0) NOT NULL,
    [IGRWSWTIT] BIT           CONSTRAINT [DF_BUTLIGRW_IGRWSWTIT] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_BUTLIGRW] PRIMARY KEY CLUSTERED ([IGRWCDPAL] ASC, [IGRWINREL] ASC, [IGRWINIDI] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUTLIGRW_METLIDI] FOREIGN KEY ([IGRWINIDI]) REFERENCES [dbo].[METLIDI] ([IDICDIDI])
);

