CREATE TABLE [dbo].[CATLHCA] (
    [HCACDCAR] CHAR (4)  NOT NULL,
    [HCADSTPN] CHAR (16) NOT NULL,
    [HCADSNOM] CHAR (30) NOT NULL,
    CONSTRAINT [PK_CATLHCA] PRIMARY KEY CLUSTERED ([HCACDCAR] ASC, [HCADSTPN] ASC, [HCADSNOM] ASC) WITH (FILLFACTOR = 90)
);

