CREATE TABLE [dbo].[CCITLIMS] (
    [IMSINEXP] INT          NOT NULL,
    [IMSSTTEL] CHAR (9)     NOT NULL,
    [IMSSTTEX] TEXT         NOT NULL,
    [IMSSTREF] VARCHAR (50) NOT NULL,
    [IMSSTCOM] TEXT         NULL,
    [IMSSTFIN] TEXT         NULL,
    CONSTRAINT [PK_CCITLIMS] PRIMARY KEY CLUSTERED ([IMSINEXP] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CCITLIMS_METLLTR] FOREIGN KEY ([IMSINEXP]) REFERENCES [dbo].[METLLTR] ([LTRINCOD])
);

