CREATE TABLE [dbo].[CCITLPRS] (
    [PRSSTUSU] VARCHAR (21)  NOT NULL,
    [PRSSTNOM] VARCHAR (255) NOT NULL,
    [PRSSTVAL] VARCHAR (255) NULL,
    CONSTRAINT [PK__CCITLPRS__4D35603F] PRIMARY KEY CLUSTERED ([PRSSTUSU] ASC, [PRSSTNOM] ASC) WITH (FILLFACTOR = 90)
);

