CREATE TABLE [dbo].[CCITLBDL] (
    [BDLINCOD] INT      IDENTITY (1, 1) NOT NULL,
    [BDLDTCRE] DATETIME CONSTRAINT [DF_CCITLBDL_BDLDTCRE] DEFAULT (getdate()) NOT NULL,
    [BDLSTTXT] TEXT     NOT NULL,
    CONSTRAINT [PK_CCITLBDL] PRIMARY KEY CLUSTERED ([BDLINCOD] ASC) WITH (FILLFACTOR = 90)
);

