CREATE TABLE [dbo].[CCITLCBE] (
    [CBEINEXP] INT           NOT NULL,
    [CBESTNOB] VARCHAR (50)  NULL,
    [CBESTCOB] VARCHAR (100) NOT NULL,
    [CBESTNIB] VARCHAR (20)  NOT NULL,
    [CBESTADB] VARCHAR (300) NOT NULL,
    [CBESTTLB] CHAR (9)      NOT NULL,
    [CBESTTLT] CHAR (9)      NULL,
    [CBESTPET] INT           NOT NULL,
    [CBESTREF] VARCHAR (50)  NOT NULL,
    [CBESTMIS] TEXT          NULL,
    CONSTRAINT [FK_CCITLCBE_CCITLPER] FOREIGN KEY ([CBESTPET]) REFERENCES [dbo].[CCITLPER] ([PERINCOD]),
    CONSTRAINT [FK_CCITLCBE_METLLTR] FOREIGN KEY ([CBEINEXP]) REFERENCES [dbo].[METLLTR] ([LTRINCOD]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Persona a la carpeta ciutadana', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CCITLCBE', @level2type = N'COLUMN', @level2name = N'CBESTPET';

