CREATE TABLE [dbo].[CCITLMIS] (
    [MISINCOD] INT           IDENTITY (1, 1) NOT NULL,
    [MISINPER] INT           NOT NULL,
    [MISSTASU] VARCHAR (255) NOT NULL,
    [MISSTTEX] TEXT          NOT NULL,
    [MISDTCRE] DATETIME      CONSTRAINT [DF_CCITLMIS_MISDTCRE] DEFAULT (getdate()) NOT NULL,
    [MISBOLLE] CHAR (1)      CONSTRAINT [DF_CCITLMIS_MISBOLLE] DEFAULT ('N') NOT NULL,
    [MISSTREM] VARCHAR (255) CONSTRAINT [DF_CCITLMIS_MISSTREM] DEFAULT ('-') NOT NULL,
    [MISBOELI] CHAR (1)      CONSTRAINT [DF_CCITLMIS_MISBOELI] DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_CCITLMIS] PRIMARY KEY CLUSTERED ([MISINCOD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CCITLMIS_CCITLPER] FOREIGN KEY ([MISINPER]) REFERENCES [dbo].[CCITLPER] ([PERINCOD]) ON DELETE CASCADE
);

