CREATE TABLE [dbo].[CCITLMAD] (
    [MADINMIS] INT NOT NULL,
    [MADINDOC] INT NOT NULL,
    CONSTRAINT [PK_CCITLMAD] PRIMARY KEY CLUSTERED ([MADINMIS] ASC, [MADINDOC] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CCITLMAD_CCITLDOC] FOREIGN KEY ([MADINDOC]) REFERENCES [dbo].[CCITLDOC] ([DOCINCOD]) ON DELETE CASCADE,
    CONSTRAINT [FK_CCITLMAD_CCITLMIS] FOREIGN KEY ([MADINMIS]) REFERENCES [dbo].[CCITLMIS] ([MISINCOD])
);

