CREATE TABLE [dbo].[COETLNOT] (
    [NOTCDCOD] INT          IDENTITY (1, 1) NOT NULL,
    [NOTINIDI] SMALLINT     CONSTRAINT [DF_COETLNOT_NOTINIDI] DEFAULT (1) NOT NULL,
    [NOTDSTIT] TEXT         NOT NULL,
    [NOTDSSUB] TEXT         NULL,
    [NOTDSTXT] TEXT         NOT NULL,
    [NOTDSRES] TEXT         NULL,
    [NOTDTANY] CHAR (20)    NOT NULL,
    [NOTDTPUB] CHAR (20)    NOT NULL,
    [NOTDTCAD] CHAR (20)    CONSTRAINT [DF_COETLNOT_NOTDTCAD] DEFAULT (dateadd(year,100,getdate())) NOT NULL,
    [NOTINUSR] VARCHAR (12) NOT NULL,
    [NOTDSFIT] TEXT         NULL,
    [NOTTPORD] INT          CONSTRAINT [DF_COETLNOT_NOTTPORD] DEFAULT (1) NOT NULL,
    [NOTINTEM] INT          NOT NULL,
    [NOTBOELI] CHAR (1)     CONSTRAINT [DF_COETLNOT_NOTBOELI] DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_COETLNOT] PRIMARY KEY CLUSTERED ([NOTCDCOD] ASC, [NOTINIDI] ASC) WITH (FILLFACTOR = 90)
);

