CREATE TABLE [dbo].[COETLTEM] (
    [TEMCDCOD] INT      NOT NULL,
    [TEMINIDI] SMALLINT NOT NULL,
    [TEMDSDES] TEXT     NOT NULL,
    [TEMDSTEX] TEXT     NULL,
    CONSTRAINT [PK_COETLTEM] PRIMARY KEY CLUSTERED ([TEMCDCOD] ASC, [TEMINIDI] ASC) WITH (FILLFACTOR = 90)
);

