CREATE TABLE [dbo].[CSTLRAC] (
    [RACINCOD] INT NOT NULL,
    [RACWNCOD] INT NOT NULL,
    CONSTRAINT [PK_CSTLRAC] PRIMARY KEY NONCLUSTERED ([RACINCOD] ASC, [RACWNCOD] ASC) WITH (FILLFACTOR = 90)
);

