CREATE TABLE [dbo].[CSTLACC] (
    [ACCINNOD] INT      NOT NULL,
    [ACCINIDI] SMALLINT NOT NULL,
    [ACCDSNOM] TEXT     NOT NULL,
    [ACCDSTXT] TEXT     NULL,
    [ACCDSOBS] TEXT     NULL,
    [ACCDSQUE] TEXT     NULL,
    [ACCDSINF] TEXT     NULL,
    CONSTRAINT [PK_CSTLACC] PRIMARY KEY NONCLUSTERED ([ACCINNOD] ASC, [ACCINIDI] ASC) WITH (FILLFACTOR = 90)
);

