CREATE TABLE [dbo].[DOTLDOM] (
    [DOMINCOD] INT           NOT NULL,
    [DOMCDTRI] INT           IDENTITY (1, 1) NOT NULL,
    [DOMDTPET] DATETIME      CONSTRAINT [DF_DOTLDOM_DOMDTPET] DEFAULT (getdate()) NULL,
    [DOMSTDNI] CHAR (9)      NOT NULL,
    [DOMINACC] INT           NOT NULL,
    [DOMSTCCO] CHAR (34)     NOT NULL,
    [DOMSTCOR] VARCHAR (100) NULL,
    [DOMSTTIP] VARCHAR (50)  NOT NULL,
    [DOMSTREF] VARCHAR (150) NOT NULL,
    [DOMSTTEL] CHAR (10)     NULL,
    CONSTRAINT [PK_DOTLDOM] PRIMARY KEY CLUSTERED ([DOMINCOD] ASC, [DOMCDTRI] ASC) WITH (FILLFACTOR = 90)
);

