CREATE TABLE [dbo].[elmostr] (
    [fany]     CHAR (4) NOT NULL,
    [ftipo]    CHAR (1) NOT NULL,
    [fdistr]   CHAR (1) NOT NULL,
    [fsecci]   CHAR (2) NOT NULL,
    [fmesa]    CHAR (1) NOT NULL,
    [fcensini] CHAR (4) NULL,
    [fcensnou] CHAR (4) NULL,
    [fvots]    CHAR (4) NULL,
    [fnul]     CHAR (4) NULL,
    [fblan]    CHAR (4) NULL,
    [fvcand1]  CHAR (4) NULL,
    [fvcand2]  CHAR (4) NULL,
    [fvcand3]  CHAR (4) NULL,
    [fvcand4]  CHAR (4) NULL,
    [fvcand5]  CHAR (4) NULL,
    [fvcand6]  CHAR (4) NULL,
    [fvcand7]  CHAR (4) NULL,
    [fvcand8]  CHAR (4) NULL,
    [fvcand9]  CHAR (4) NULL,
    [fvcand10] CHAR (4) NULL,
    [fvcand11] CHAR (4) NULL,
    [fvcand12] CHAR (4) NULL,
    [fvcand13] CHAR (4) NULL,
    [fvcand14] CHAR (4) NULL,
    [fvcand15] CHAR (4) NULL,
    [fvcand16] CHAR (4) NULL,
    [fvcand17] CHAR (4) NULL,
    [fvcand18] CHAR (4) NULL,
    [fvcand19] CHAR (4) NULL,
    [fvcand20] CHAR (4) NULL,
    [fvcand21] CHAR (4) NULL,
    [fvcand22] CHAR (4) NULL,
    [fvcand23] CHAR (4) NULL,
    [fvcand24] CHAR (4) NULL,
    [fvcand25] CHAR (4) NULL,
    [fvcand26] CHAR (4) NULL,
    [fvcand27] CHAR (4) NULL,
    [fvcand28] CHAR (4) NULL,
    [fvcand29] CHAR (4) NULL,
    [fvcand30] CHAR (4) NULL,
    [fvcand31] CHAR (4) NULL,
    [fvcand32] CHAR (4) NULL,
    [fvcand33] CHAR (4) NULL,
    [fvcand34] CHAR (4) NULL,
    [fvcand35] CHAR (4) NULL,
    [fvcand36] CHAR (4) NULL,
    [fvcand37] CHAR (4) NULL,
    [fvcand38] CHAR (4) NULL,
    [fvcand39] CHAR (4) NULL,
    [fvcand40] CHAR (4) NULL,
    [fvcand41] CHAR (4) NULL,
    [fvcand42] CHAR (4) NULL,
    [fvcand43] CHAR (4) NULL,
    [fvcand44] CHAR (4) NULL,
    [fvcand45] CHAR (4) NULL,
    [fvcand46] CHAR (4) NULL,
    [fvcand47] CHAR (4) NULL,
    [fvcand48] CHAR (4) NULL,
    [fvcand49] CHAR (4) NULL,
    [fvcand50] CHAR (4) NULL,
    [fvcand51] CHAR (4) NULL,
    [fvcand52] CHAR (4) NULL,
    [fvcand53] CHAR (4) NULL,
    [fvcand54] CHAR (4) NULL,
    [fvcand55] CHAR (4) NULL,
    [fvcand56] CHAR (4) NULL,
    [fhora]    CHAR (5) NULL,
    [fdefini]  CHAR (1) NULL
);

