CREATE TABLE [dbo].[ENQTLENQ] (
    [ENQINCOD] INT      IDENTITY (1, 1) NOT NULL,
    [ENQDTINI] DATETIME DEFAULT (null) NULL,
    [ENQDTFIN] DATETIME DEFAULT (null) NULL,
    PRIMARY KEY CLUSTERED ([ENQINCOD] ASC) WITH (FILLFACTOR = 90)
);

