CREATE TABLE [dbo].[ENQTLRES] (
    [RESINOMP] INT          NOT NULL,
    [RESSTPRE] VARCHAR (50) NOT NULL,
    [RESSTRES] TEXT         NOT NULL,
    PRIMARY KEY CLUSTERED ([RESINOMP] ASC, [RESSTPRE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__ENQTLRES__RESINO__1293BD5E] FOREIGN KEY ([RESINOMP]) REFERENCES [dbo].[ENQTLOMP] ([OMPINCOD])
);

