CREATE TABLE [dbo].[ENQTLOMP] (
    [OMPINCOD] INT        IDENTITY (1, 1) NOT NULL,
    [OMPINENQ] INT        NULL,
    [OMPDTOMP] DATETIME   CONSTRAINT [DF__ENQTLOMP__OMPDTO__0DCF0841] DEFAULT (getdate()) NULL,
    [OMPSTUSU] CHAR (100) CONSTRAINT [DF__ENQTLOMP__OMPSTU__0EC32C7A] DEFAULT (null) NULL,
    CONSTRAINT [PK__ENQTLOMP__0CDAE408] PRIMARY KEY CLUSTERED ([OMPINCOD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__ENQTLOMP__OMPINE__0FB750B3] FOREIGN KEY ([OMPINENQ]) REFERENCES [dbo].[ENQTLENQ] ([ENQINCOD])
);

