CREATE TABLE [dbo].[FOTLMIS] (
    [MISCDCOD] INT        NOT NULL,
    [MISCDMIS] INT        IDENTITY (1, 1) NOT NULL,
    [MISDSTIT] CHAR (100) NULL,
    [MISCDREF] INT        NULL,
    [MISDSTXT] TEXT       NULL,
    [MISCDUSU] CHAR (40)  NULL,
    [MISDTDAT] DATETIME   NULL,
    [MISDSALI] CHAR (50)  NULL,
    [MISCDDIS] INT        NULL,
    [MISDSRES] CHAR (40)  CONSTRAINT [DF_FOTLMIS_MISDSRES] DEFAULT ('Tots') NULL,
    CONSTRAINT [PK_FOTLMIS] PRIMARY KEY CLUSTERED ([MISCDMIS] ASC) WITH (FILLFACTOR = 90)
);

