CREATE TABLE [dbo].[FOTOSYTEMES] (
    [FYTINFOT] NUMERIC (18) NOT NULL,
    [FYTCDTEM] NUMERIC (18) NOT NULL,
    [FYTDSTEM] TEXT         NOT NULL,
    CONSTRAINT [PK_FOTOSYTEMES] PRIMARY KEY CLUSTERED ([FYTINFOT] ASC, [FYTCDTEM] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_FOTOSYTEMES_FOTOS] FOREIGN KEY ([FYTINFOT]) REFERENCES [dbo].[FOTOS] ([Numero]),
    CONSTRAINT [FK_FOTOSYTEMES_TEMES] FOREIGN KEY ([FYTCDTEM]) REFERENCES [dbo].[TEMES] ([TEMCDTEM])
);

