CREATE TABLE [dbo].[INTLDAC] (
    [DACCDACT] INT           NOT NULL,
    [DACDHANY] INT           NOT NULL,
    [DACCDDIA] SMALLDATETIME NOT NULL,
    [DACDHFIN] SMALLDATETIME NOT NULL,
    CONSTRAINT [PK_INTLDAC] PRIMARY KEY CLUSTERED ([DACCDACT] ASC, [DACDHANY] ASC, [DACCDDIA] ASC) WITH (FILLFACTOR = 90)
);

