CREATE TABLE [dbo].[INTLACT_040908] (
    [ACTINACT] INT             NOT NULL,
    [ACTDHANY] INT             NOT NULL,
    [ACTDHINI] SMALLDATETIME   NOT NULL,
    [ACTDSTIT] NVARCHAR (1000) NOT NULL,
    [ACTDSDES] TEXT            NULL,
    [ACTDSAFO] INT             NOT NULL,
    [ACTDSMIN] INT             NOT NULL,
    [ACTDHDUH] SMALLINT        NOT NULL,
    [ACTDHDUM] SMALLINT        NOT NULL,
    [ACTWNPPU] FLOAT (53)      NOT NULL,
    [ACTDHFIN] SMALLDATETIME   NOT NULL,
    [ACTDSANU] CHAR (10)       NOT NULL,
    [ACTWNPCO] FLOAT (53)      NULL,
    [ACTWNPPR] FLOAT (53)      NULL,
    [ACTCDENT] INT             NOT NULL,
    [ACTDSPDF] NVARCHAR (100)  NULL,
    [ACTTPRES] CHAR (10)       NOT NULL,
    [ACTDSOBS] TEXT            NULL,
    [ACTCDACU] INT             NOT NULL,
    [ACTDSOBJ] TEXT            NULL,
    [ACTINCPR] INT             NULL,
    [ACTDSCPR] TEXT            NULL,
    [ACTINMON] INT             NULL,
    [ACTDSMON] TEXT            NULL,
    [ACTINMSO] INT             NULL,
    [ACTDSMSO] TEXT            NULL,
    [ACTDSNLR] NVARCHAR (100)  NULL,
    [ACTDSLLR] NVARCHAR (100)  NULL,
    [ACTDSPLR] NVARCHAR (100)  NULL,
    [ACTDSCAR] TEXT            NULL,
    [ACTDSCOC] TEXT            NULL,
    [ACTDSCOP] TEXT            NULL,
    [ACTDSCOA] TEXT            NULL,
    [ACTINVNE] INT             NULL,
    [ACTDSVNE] TEXT            NULL,
    [ACTINRED] INT             NULL,
    [ACTINRCC] INT             NULL,
    [ACTINAMI] INT             NULL,
    [ACTDSMOD] VARCHAR (500)   NULL
);

