CREATE TABLE [dbo].[INTLGRA] (
    [GRACDECD] INT           IDENTITY (1, 1) NOT NULL,
    [GRACDESC] INT           NOT NULL,
    [GRACDACT] INT           NOT NULL,
    [GRADHANY] INT           NOT NULL,
    [GRACDDIA] SMALLDATETIME NOT NULL,
    [GRADSRES] SMALLINT      NULL,
    [GRADSREM] SMALLINT      NULL,
    [GRADSREP] SMALLINT      NULL,
    [GRADSASI] SMALLINT      NULL,
    [GRATPPAG] CHAR (1)      NULL,
    [GRACDGRU] INT           NOT NULL,
    [GRADSLIN] CHAR (1)      NULL,
    [GRADSREE] CHAR (100)    NULL,
    [GRATPEST] CHAR (4)      NOT NULL,
    [GRADSBAI] TEXT          NULL,
    [GRATSTIM] DATETIME      NULL,
    [GRADSOBS] TEXT          NULL,
    CONSTRAINT [PK_INTLGRA] PRIMARY KEY CLUSTERED ([GRACDECD] ASC) WITH (FILLFACTOR = 90)
);

