CREATE TABLE [dbo].[LHFORMIS] (
    [INCOD]    INT            IDENTITY (1, 1) NOT NULL,
    [INFOR]    INT            NOT NULL,
    [INMIS]    INT            NULL,
    [STNOM]    VARCHAR (2000) NOT NULL,
    [DTCRE]    DATETIME       CONSTRAINT [DF_LHFORMIS_DTCRE] DEFAULT (getdate()) NOT NULL,
    [STUSU]    VARCHAR (20)   NOT NULL,
    [STTXT]    TEXT           NULL,
    [BOBLO]    CHAR (1)       CONSTRAINT [DF_LHFORMIS_BOBLO] DEFAULT ('0') NOT NULL,
    [BOELI]    CHAR (1)       CONSTRAINT [DF_LHFORMIS_BOELI] DEFAULT ('0') NOT NULL,
    [MISDSFIT] TEXT           NULL,
    [MISDSNFI] VARCHAR (200)  CONSTRAINT [DF_LHFORMIS_MISDSNFI] DEFAULT ('Nom del fitxer') NULL,
    [MISWNTHO] SMALLINT       CONSTRAINT [DF_LHFORMIS_MISWNTHO] DEFAULT (0) NULL,
    CONSTRAINT [PK_LHFORMIS] PRIMARY KEY CLUSTERED ([INCOD] ASC) WITH (FILLFACTOR = 90)
);

