CREATE TABLE [dbo].[LHFORFOR] (
    [INCOD] INT            NOT NULL,
    [INCAT] INT            NOT NULL,
    [STNOM] VARCHAR (8000) NOT NULL,
    [DTCRE] DATETIME       CONSTRAINT [DF_LHFORFOR_DTCRE] DEFAULT (getdate()) NOT NULL,
    [STUSU] VARCHAR (20)   NOT NULL,
    [BOBLO] BIT            CONSTRAINT [DF_LHFORFOR_BOBLO] DEFAULT ('0') NOT NULL,
    [BOELI] BIT            CONSTRAINT [DF_LHFORFOR_BOELI] DEFAULT ('0') NOT NULL,
    [STDES] TEXT           NULL,
    [INVIS] INT            CONSTRAINT [DF_LHFORFOR_INVIS] DEFAULT (1) NULL,
    CONSTRAINT [PK_LHFORFOR] PRIMARY KEY CLUSTERED ([INCOD] ASC) WITH (FILLFACTOR = 90)
);

