CREATE TABLE [dbo].[MAILINGNOV] (
    [ENTITAT]   NVARCHAR (255) NULL,
    [N COMPLET] NVARCHAR (255) NULL,
    [NOM]       NVARCHAR (255) NULL,
    [CÀRREC]    NVARCHAR (255) NULL,
    [TRAT]      NVARCHAR (255) NULL,
    [COGNOM]    NVARCHAR (255) NULL,
    [EMAIL]     NVARCHAR (255) NULL,
    [ADREÇA]    NVARCHAR (255) NULL,
    [CP]        NVARCHAR (255) NULL,
    [GRUP]      NVARCHAR (255) NULL,
    [POBLACIO]  NVARCHAR (255) NULL
);

