CREATE TABLE [dbo].[MAITLTRA] (
    [TRAINLTR] INT          NOT NULL,
    [TRAINLLI] INT          NOT NULL,
    [TRASTDES] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_MAITLTRA] PRIMARY KEY CLUSTERED ([TRAINLTR] ASC) WITH (FILLFACTOR = 90)
);

