CREATE TABLE [dbo].[METLTBL] (
    [TBLINTFU] INT      NOT NULL,
    [TBLDSTXT] CHAR (8) NOT NULL,
    [TBLINNOD] INT      CONSTRAINT [DF_METLTBL_PLTINNOD] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_METLTBL] PRIMARY KEY NONCLUSTERED ([TBLINTFU] ASC) WITH (FILLFACTOR = 90)
);

