CREATE TABLE [dbo].[METLNCI] (
    [NCIINNOD] INT  NOT NULL,
    [NCIDSNOM] TEXT NOT NULL,
    [NCICDAAP] INT  NOT NULL,
    [NCICDADE] INT  NOT NULL,
    CONSTRAINT [PK_METLNCI] PRIMARY KEY NONCLUSTERED ([NCIINNOD] ASC) WITH (FILLFACTOR = 90)
);

