CREATE TABLE [dbo].[METLACC] (
    [ACCINCOD] INT  IDENTITY (1, 1) NOT NULL,
    [ACCDSNOM] TEXT NOT NULL,
    [ACCDSTXT] TEXT NOT NULL,
    CONSTRAINT [PK_METLACC] PRIMARY KEY NONCLUSTERED ([ACCINCOD] ASC) WITH (FILLFACTOR = 90)
);

