CREATE TABLE [dbo].[METLASS_REVISIO] (
    [ASSINCOD] INT          IDENTITY (1, 1) NOT NULL,
    [ASSCDTPA] INT          NOT NULL,
    [ASSCDNOD] DECIMAL (18) NOT NULL,
    [ASSCDTIP] INT          NOT NULL,
    [ASSCDNRL] DECIMAL (18) NOT NULL,
    CONSTRAINT [PK_METLASS_REVISIO] PRIMARY KEY CLUSTERED ([ASSINCOD] ASC) WITH (FILLFACTOR = 90)
);

