CREATE TABLE [dbo].[METLPRE] (
    [PREINNOD] NUMERIC (18) NOT NULL,
    [PREDHDAT] DATETIME     NOT NULL,
    [PREINCOL] INT          NOT NULL,
    [PREDSHFI] VARCHAR (5)  NULL,
    [PREIMPRE] FLOAT (53)   NOT NULL,
    [PREDSOBS] TEXT         NULL,
    CONSTRAINT [PK_METLPRE] PRIMARY KEY CLUSTERED ([PREINNOD] ASC, [PREDHDAT] ASC, [PREINCOL] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_METLPRE_METLNOD] FOREIGN KEY ([PREINNOD]) REFERENCES [dbo].[METLNOD] ([NODINNOD])
);

