CREATE TABLE [dbo].[METLEQP] (
    [EQPINACT] NUMERIC (18) NOT NULL,
    [EQPINDIR] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_METLEQP] PRIMARY KEY CLUSTERED ([EQPINACT] ASC, [EQPINDIR] ASC) WITH (FILLFACTOR = 90)
);

