CREATE TABLE [dbo].[METLCOD] (
    [CODINTIP] SMALLINT CONSTRAINT [DF_METLCOD_CODINTIP] DEFAULT (1) NOT NULL,
    [CODINCOD] SMALLINT IDENTITY (1, 1) NOT NULL,
    [CODDSTXT] TEXT     NOT NULL,
    CONSTRAINT [PK_METLCOD] PRIMARY KEY NONCLUSTERED ([CODINTIP] ASC, [CODINCOD] ASC) WITH (FILLFACTOR = 90)
);

