CREATE TABLE [dbo].[METLMIS] (
    [MISINNOD] INT      NOT NULL,
    [MISINCOD] INT      NOT NULL,
    [MISDSTIT] TEXT     NOT NULL,
    [MISCDPCR] INT      NOT NULL,
    [MISDTDAT] DATETIME NOT NULL,
    [MISDSTXT] TEXT     NOT NULL,
    [MISDSBAP] CHAR (1) NOT NULL,
    [MISDSBCA] CHAR (1) NOT NULL,
    [MISDSBES] CHAR (1) NOT NULL,
    [MISDSBED] CHAR (1) NOT NULL,
    [MISDSBLH] DATETIME NULL,
    [MISDSBLU] INT      NOT NULL,
    [MISCDRCI] INT      NOT NULL,
    CONSTRAINT [PK_METLMIS] PRIMARY KEY NONCLUSTERED ([MISINNOD] ASC) WITH (FILLFACTOR = 90)
);

