CREATE TABLE [dbo].[METLTEL] (
    [TELINDIR] NUMERIC (18) NOT NULL,
    [TELINIDI] SMALLINT     NOT NULL,
    [TELDSNUM] VARCHAR (50) NOT NULL,
    [TELDSIDE] INT          IDENTITY (1, 1) NOT NULL,
    [TELDSTIP] VARCHAR (50) NOT NULL,
    [TELDSOBS] TEXT         NULL,
    [TELSWPUB] CHAR (1)     CONSTRAINT [DF_METLTEL_TELDSPUB] DEFAULT ('N') NOT NULL,
    [TELDSCOM] TEXT         NULL,
    [TELINPOS] SMALLINT     NULL,
    CONSTRAINT [PK_METLTEL] PRIMARY KEY CLUSTERED ([TELINDIR] ASC, [TELINIDI] ASC, [TELDSNUM] ASC, [TELDSIDE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_METLTEL_METLDIR] FOREIGN KEY ([TELINDIR], [TELINIDI]) REFERENCES [dbo].[METLDIR] ([DIRINNOD], [DIRINIDI])
);

