CREATE TABLE [dbo].[METLPER2] (
    [PERCDREL]  NUMERIC (18) NOT NULL,
    [PERINORG]  INT          NOT NULL,
    [PERINNOD]  NUMERIC (18) NOT NULL,
    [PERCDPE1]  SMALLINT     NOT NULL,
    [PERCDPE2]  SMALLINT     NOT NULL,
    [PERCDPE3]  SMALLINT     NOT NULL,
    [PERCDPE4]  SMALLINT     NOT NULL,
    [PERCDPE5]  SMALLINT     NOT NULL,
    [PERCDPE6]  SMALLINT     NOT NULL,
    [PERCDPE7]  SMALLINT     NOT NULL,
    [PERCDPE8]  SMALLINT     NOT NULL,
    [PERCDPE9]  SMALLINT     NOT NULL,
    [PERCDPE10] SMALLINT     NOT NULL,
    CONSTRAINT [PK_METLPER2] PRIMARY KEY NONCLUSTERED ([PERCDREL] ASC, [PERINORG] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_METLPER2_METLNOD] FOREIGN KEY ([PERINNOD]) REFERENCES [dbo].[METLNOD] ([NODINNOD]) ON DELETE CASCADE NOT FOR REPLICATION,
    CONSTRAINT [FK_METLPER2_METLREL] FOREIGN KEY ([PERCDREL]) REFERENCES [dbo].[METLREL] ([RELINCOD]) ON DELETE CASCADE NOT FOR REPLICATION
);

