CREATE TABLE [dbo].[METLLCE] (
    [LCEINNOD] INT           NOT NULL,
    [LCEINIDI] SMALLINT      NOT NULL,
    [LCEINLCW] VARCHAR (500) NOT NULL,
    [LCEDSEXE] TEXT          NOT NULL,
    [LCEDTFEC] DATETIME      NOT NULL,
    [LCEDSCSS] TEXT          CONSTRAINT [DF_METLLCE_LCEDSCSS] DEFAULT ('') NOT NULL,
    [LCEDTCAD] DATETIME      CONSTRAINT [DF_METLLCE_LCEDTCAD] DEFAULT ('1/1/1900') NOT NULL,
    CONSTRAINT [PK_METLLCE] PRIMARY KEY CLUSTERED ([LCEINNOD] ASC, [LCEINIDI] ASC, [LCEINLCW] ASC)
);

