CREATE TABLE [dbo].[METLCSS] (
    [CSSINTIP] SMALLINT      NOT NULL,
    [CSSINCOD] INT           IDENTITY (1, 1) NOT NULL,
    [CSSDSTXT] VARCHAR (250) NULL,
    [CSSDSTHO] INT           NOT NULL,
    [CSSDSTHP] INT           CONSTRAINT [DF_METLCSS_CSSDSTHP] DEFAULT ((0)) NOT NULL,
    [CSSDSCSS] VARCHAR (400) NULL,
    [CSSWNWIG] SMALLINT      NULL,
    [CSSWNFLT] SMALLINT      NULL,
    [CSSWNSUS] SMALLINT      CONSTRAINT [DF_METLCSS_CSSWNSUS] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_METLCSS] PRIMARY KEY CLUSTERED ([CSSINTIP] ASC, [CSSINCOD] ASC)
);

