CREATE TABLE [dbo].[METLIRD] (
    [IRDINNOD] NUMERIC (18) NOT NULL,
    [IRDINIDI] SMALLINT     NOT NULL,
    [IRDINDOC] INT          NOT NULL,
    CONSTRAINT [PK_METLIRD] PRIMARY KEY NONCLUSTERED ([IRDINNOD] ASC, [IRDINIDI] ASC, [IRDINDOC] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_METLIRD_METLNOT] FOREIGN KEY ([IRDINNOD], [IRDINIDI]) REFERENCES [dbo].[METLNOT] ([NOTINNOD], [NOTINIDI])
);

