CREATE TABLE [dbo].[METLPEL] (
    [PELCDREL] NUMERIC (18) NOT NULL,
    [PELCDVER] SMALLINT     NOT NULL,
    [PELINORG] INT          NOT NULL,
    [PELINHER] INT          NOT NULL,
    CONSTRAINT [PK_METLPEL] PRIMARY KEY NONCLUSTERED ([PELCDREL] ASC, [PELCDVER] ASC, [PELINORG] ASC, [PELINHER] ASC) WITH (FILLFACTOR = 90)
);

