CREATE TABLE [dbo].[METLMAN] (
    [MANINMAN] NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [MANCDREL] NUMERIC (18) CONSTRAINT [DF_METLMAN_MANCDREL] DEFAULT (0) NULL,
    [MANCDIDI] SMALLINT     NOT NULL,
    [MANDTDAT] DATETIME     NOT NULL,
    [MANCDNOD] NUMERIC (18) CONSTRAINT [DF_METLMAN_MANCDNOD] DEFAULT (0) NULL,
    [MANDTTIM] DATETIME     NULL,
    [MANDTTEM] INT          CONSTRAINT [DF_METLMAN_MANDTTEM2] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_METLMAN_1] PRIMARY KEY CLUSTERED ([MANINMAN] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [MANINMAN_MANDTDAT]
    ON [dbo].[METLMAN]([MANCDNOD] ASC, [MANDTTEM] ASC, [MANDTDAT] ASC)
    INCLUDE([MANINMAN], [MANCDREL], [MANCDIDI], [MANDTTIM]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'timestamp', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLMAN', @level2type = N'COLUMN', @level2name = N'MANDTTIM';

