CREATE TABLE [dbo].[METLDEB] (
    [CODI] INT      IDENTITY (1, 1) NOT NULL,
    [TEXT] TEXT     NOT NULL,
    [data] DATETIME NOT NULL,
    CONSTRAINT [PK_METLDEB] PRIMARY KEY CLUSTERED ([CODI] ASC)
);

