CREATE TABLE [dbo].[METLERR] (
    [ERRINCOD] INT       IDENTITY (1, 1) NOT NULL,
    [ERRTPORG] CHAR (50) CONSTRAINT [DF_METLERR_ERRTPORG] DEFAULT ('') NOT NULL,
    [ERRDSSRC] TEXT      CONSTRAINT [DF_METLERR_ERRDSCOD] DEFAULT ('') NOT NULL,
    [ERRDSDES] TEXT      CONSTRAINT [DF_METLERR_ERRDSDES] DEFAULT ('') NOT NULL,
    [ERRDTHOR] DATETIME  CONSTRAINT [DF_METLERR_ERRDTHOR] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_METLERR] PRIMARY KEY CLUSTERED ([ERRINCOD] DESC) WITH (FILLFACTOR = 90)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Codi autonumèric', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLERR', @level2type = N'COLUMN', @level2name = N'ERRINCOD';

