CREATE TABLE [dbo].[METLNOD_REVISIO] (
    [NODINNOD] DECIMAL (18)   NOT NULL,
    [NODCDTIP] INT            NOT NULL,
    [NODCDUSR] CHAR (9)       NOT NULL,
    [NODDTTIM] CHAR (20)      NULL,
    [NODDSTXT] VARCHAR (1024) NULL,
    [NODSWVIS] SMALLINT       NOT NULL,
    [NODDTTMS] BINARY (8)     NULL,
    CONSTRAINT [PK_METLNOD_REVISIO] PRIMARY KEY CLUSTERED ([NODINNOD] ASC) WITH (FILLFACTOR = 90)
);

