CREATE TABLE [dbo].[METLIDR] (
    [IDRINNOD] INT      NOT NULL,
    [IDRINIDI] SMALLINT NOT NULL,
    [IDRCDCAR] INT      NOT NULL,
    [IDRCDDIS] INT      NOT NULL,
    [IDRCDBAR] INT      NOT NULL,
    [IDRDHFEC] DATETIME NOT NULL,
    [IDRCDSIT] INT      NULL,
    CONSTRAINT [PK_BUTLDIR] PRIMARY KEY CLUSTERED ([IDRINNOD] ASC, [IDRINIDI] ASC) WITH (FILLFACTOR = 90)
);

