CREATE TABLE [dbo].[METLFCI] (
    [FCIINNOD] INT       NOT NULL,
    [FCIDSNOM] TEXT      NOT NULL,
    [FCITPAPE] CHAR (1)  CONSTRAINT [DF_METLFCI_FCITPAPE] DEFAULT ('N') NOT NULL,
    [FCITPCPE] CHAR (1)  CONSTRAINT [DF_METLFCI_FCITPAPE1] DEFAULT ('N') NOT NULL,
    [FCITPURG] CHAR (1)  CONSTRAINT [DF_METLFCI_FCITPCPE1] DEFAULT ('N') NOT NULL,
    [FCIWNTMD] SMALLINT  CONSTRAINT [DF_METLFCI_FCITPCPE2] DEFAULT (0) NOT NULL,
    [FCIWNTMH] SMALLINT  CONSTRAINT [DF_METLFCI_FCIWNTMD1] DEFAULT (0) NOT NULL,
    [FCIDSMA1] TEXT      CONSTRAINT [DF_METLFCI_FCIDSMA1] DEFAULT ('') NOT NULL,
    [FCIDSMA2] TEXT      CONSTRAINT [DF_METLFCI_FCIDSMA2] DEFAULT ('') NOT NULL,
    [FCIDSMIC] TEXT      CONSTRAINT [DF_METLFCI_FCIDSMIC] DEFAULT ('') NOT NULL,
    [FCIDSMIM] TEXT      CONSTRAINT [DF_METLFCI_FCIDSMIM] DEFAULT ('') NOT NULL,
    [FCICDREG] INT       CONSTRAINT [DF_METLFCI_FCICDREG] DEFAULT (0) NOT NULL,
    [FCIDTANY] DATETIME  NOT NULL,
    [FCIDSUSR] CHAR (10) NOT NULL
);

