CREATE TABLE [dbo].[METLEST] (
    [ESTINNOD] INT       NOT NULL,
    [ESTCDORD] CHAR (10) NOT NULL,
    [ESTTPTIP] SMALLINT  CONSTRAINT [DF_METLEST_ESTTPTIP] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_METLEST] PRIMARY KEY NONCLUSTERED ([ESTINNOD] ASC, [ESTCDORD] ASC) WITH (FILLFACTOR = 90)
);

