CREATE TABLE [dbo].[METLATR] (
    [ATRCDLTR] INT      NOT NULL,
    [ATRINCOD] INT      NOT NULL,
    [ATRTPEST] SMALLINT NOT NULL,
    [ATRTPFEC] DATETIME NOT NULL,
    [ATRDSTXT] TEXT     NOT NULL,
    [ATRDSXML] TEXT     NULL
);


GO
CREATE NONCLUSTERED INDEX [ATR_LTR, sysname,>]
    ON [dbo].[METLATR]([ATRCDLTR] ASC);

