CREATE TABLE [dbo].[METLREL] (
    [RELINCOD] NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [RELCDARB] SMALLINT      NOT NULL,
    [RELCDVER] SMALLINT      NOT NULL,
    [RELINPAR] NUMERIC (18)  NOT NULL,
    [RELINFIL] NUMERIC (18)  NOT NULL,
    [RELCDHER] VARCHAR (600) CONSTRAINT [DF_METLREL_RELCDHER] DEFAULT ('') NOT NULL,
    [RELCDEST] SMALLINT      CONSTRAINT [DF_METLREL_RELCDEST] DEFAULT ((-1)) NOT NULL,
    [RELCDORD] INT           CONSTRAINT [DF_METLREL_RELCDORD] DEFAULT (0) NOT NULL,
    [RELCDSIT] SMALLINT      CONSTRAINT [DF_METLREL_RELCDSIT] DEFAULT (1) NOT NULL,
    [RELDSFIT] VARCHAR (255) NULL,
    [RELCDEAL] SMALLINT      CONSTRAINT [DF_METLREL_RELCDEAL] DEFAULT (0) NOT NULL,
    [RELINPLA] INT           NULL,
    [RELSWVIS] SMALLINT      CONSTRAINT [DF_METLREL_RELSWVIS] DEFAULT (1) NOT NULL,
    [RELCDRSU] NUMERIC (18)  NULL,
    CONSTRAINT [PK_METLREL] PRIMARY KEY NONCLUSTERED ([RELINCOD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_METLREL_METLNOD] FOREIGN KEY ([RELINFIL]) REFERENCES [dbo].[METLNOD] ([NODINNOD]) NOT FOR REPLICATION,
    CONSTRAINT [FK_METLREL_METLNOD1] FOREIGN KEY ([RELINPAR]) REFERENCES [dbo].[METLNOD] ([NODINNOD]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[METLREL] NOCHECK CONSTRAINT [FK_METLREL_METLNOD];


GO
ALTER TABLE [dbo].[METLREL] NOCHECK CONSTRAINT [FK_METLREL_METLNOD1];


GO
CREATE CLUSTERED INDEX [_dta_index_METLREL_c_7_1023394765__K1]
    ON [dbo].[METLREL]([RELINCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [METLREL2]
    ON [dbo].[METLREL]([RELINFIL] ASC, [RELCDHER] ASC, [RELCDSIT] ASC, [RELCDORD] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K9_K5_K1_K6]
    ON [dbo].[METLREL]([RELCDSIT] ASC, [RELINFIL] ASC, [RELINCOD] ASC, [RELCDHER] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K5_K9_K1_K6]
    ON [dbo].[METLREL]([RELINFIL] ASC, [RELCDSIT] ASC, [RELINCOD] ASC, [RELCDHER] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K5_K9_K6_K1_K13_K4]
    ON [dbo].[METLREL]([RELINFIL] ASC, [RELCDSIT] ASC, [RELCDHER] ASC, [RELINCOD] ASC, [RELSWVIS] ASC, [RELINPAR] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K13_K5_K9]
    ON [dbo].[METLREL]([RELSWVIS] ASC, [RELINFIL] ASC, [RELCDSIT] ASC);


GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINCOD], [RELINFIL], [RELSWVIS]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDSIT]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINCOD], [RELINFIL], [RELCDHER], [RELSWVIS]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDSIT_RELSWVIS]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINCOD], [RELINFIL], [RELCDHER], [RELSWVIS]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K5_K9_K6]
    ON [dbo].[METLREL]([RELINFIL] ASC, [RELCDSIT] ASC, [RELCDHER] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_METLREL_7_1023394765__K5_K1_K9]
    ON [dbo].[METLREL]([RELINFIL] ASC, [RELINCOD] ASC, [RELCDSIT] ASC);


GO
CREATE NONCLUSTERED INDEX [idx_METLREL_RELCDSIT]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINFIL], [RELCDRSU]);


GO
CREATE NONCLUSTERED INDEX [IDX_RELCDSIT_RELCDRSU]
    ON [dbo].[METLREL]([RELCDSIT] ASC, [RELCDRSU] ASC)
    INCLUDE([RELINFIL]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDHER]
    ON [dbo].[METLREL]([RELCDHER] ASC)
    INCLUDE([RELINCOD]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDRSU]
    ON [dbo].[METLREL]([RELCDRSU] ASC);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDSIT, sysname,>]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINFIL], [RELCDHER], [RELCDRSU]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDSIT_RELCDORD_RELCDRSU]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINFIL], [RELCDORD], [RELCDRSU]);


GO
CREATE NONCLUSTERED INDEX [RELCDRSU_RELCDSIT]
    ON [dbo].[METLREL]([RELCDRSU] ASC, [RELCDSIT] ASC);


GO
CREATE NONCLUSTERED INDEX [RELCDHER_RELCDSIT_RELCDEST]
    ON [dbo].[METLREL]([RELCDEST] ASC, [RELCDSIT] ASC)
    INCLUDE([RELINCOD], [RELCDARB], [RELCDVER], [RELINPAR], [RELINFIL], [RELCDHER], [RELCDORD], [RELDSFIT], [RELCDEAL], [RELINPLA], [RELSWVIS], [RELCDRSU]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELCDSIT_RELCDHER]
    ON [dbo].[METLREL]([RELCDSIT] ASC)
    INCLUDE([RELINFIL], [RELCDHER], [RELCDORD]);


GO
CREATE NONCLUSTERED INDEX [METLREL_RELSWVIS_RELCDSIT]
    ON [dbo].[METLREL]([RELSWVIS] ASC, [RELCDSIT] ASC)
    INCLUDE([RELINFIL], [RELCDHER]);


GO
CREATE STATISTICS [_dta_stat_1023394765_5_1_4_9_6]
    ON [dbo].[METLREL]([RELINFIL], [RELINCOD], [RELINPAR], [RELCDSIT], [RELCDHER]);


GO
CREATE STATISTICS [_dta_stat_1023394765_9_6_13_5]
    ON [dbo].[METLREL]([RELCDSIT], [RELCDHER], [RELSWVIS], [RELINFIL]);


GO
CREATE STATISTICS [_dta_stat_1023394765_9_6_5_1_13_4]
    ON [dbo].[METLREL]([RELCDSIT], [RELCDHER], [RELINFIL], [RELINCOD], [RELSWVIS], [RELINPAR]);


GO
CREATE STATISTICS [_dta_stat_1023394765_1_4]
    ON [dbo].[METLREL]([RELINCOD], [RELINPAR]);


GO
CREATE STATISTICS [_dta_stat_1023394765_4_13_1_5_9]
    ON [dbo].[METLREL]([RELINPAR], [RELSWVIS], [RELINCOD], [RELINFIL], [RELCDSIT]);


GO
CREATE STATISTICS [_dta_stat_1023394765_9_13]
    ON [dbo].[METLREL]([RELCDSIT], [RELSWVIS]);


GO
CREATE STATISTICS [_dta_stat_1023394765_9_13_5_1]
    ON [dbo].[METLREL]([RELCDSIT], [RELSWVIS], [RELINFIL], [RELINCOD]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nom del fitxer publicat', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLREL', @level2type = N'COLUMN', @level2name = N'RELDSFIT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Posició dins de l''estructura per a un autolink', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLREL', @level2type = N'COLUMN', @level2name = N'RELCDEAL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Relació visible a internet?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLREL', @level2type = N'COLUMN', @level2name = N'RELSWVIS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'codi de relació superior', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'METLREL', @level2type = N'COLUMN', @level2name = N'RELCDRSU';

