CREATE TABLE [dbo].[METLORG] (
    [ORGINACT] NUMERIC (18) NOT NULL,
    [ORGINDIR] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_METLORG] PRIMARY KEY CLUSTERED ([ORGINACT] ASC, [ORGINDIR] ASC) WITH (FILLFACTOR = 90)
);

