CREATE TABLE [dbo].[METLENC] (
    [ENCINNOD] NUMERIC (18) NOT NULL,
    [ENCDSCON] INT          CONSTRAINT [DF_METLENC_ENCDSCON] DEFAULT (0) NOT NULL,
    [ENCDSVAL] INT          NOT NULL,
    CONSTRAINT [PK_METLENC] PRIMARY KEY CLUSTERED ([ENCINNOD] ASC) WITH (FILLFACTOR = 90)
);

