CREATE TABLE [dbo].[METLPCR] (
    [PCRINCOD] NUMERIC (18) NOT NULL,
    [PCRINORG] INT          NOT NULL,
    [PCRDTDAT] DATETIME     NOT NULL,
    [PCRCDFCI] INT          NOT NULL,
    [PCRCDRCI] INT          CONSTRAINT [DF_METLPCR_PCRCDRCI] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_METLPCR] PRIMARY KEY NONCLUSTERED ([PCRINCOD] ASC) WITH (FILLFACTOR = 90)
);

