CREATE TABLE [dbo].[METLBSG] (
    [BSGCDLTR] INT      NOT NULL,
    [BSGDSSUG] TEXT     NOT NULL,
    [BSGTPRSP] CHAR (1) NOT NULL,
    CONSTRAINT [PK_METLBSG] PRIMARY KEY CLUSTERED ([BSGCDLTR] ASC) WITH (FILLFACTOR = 90)
);

