CREATE TABLE [dbo].[METLOPI] (
    [OPICDCOD] INT             IDENTITY (1, 1) NOT NULL,
    [OPIINNOD] INT             NOT NULL,
    [OPICDUSR] NVARCHAR (50)   NOT NULL,
    [OPIDTDAT] DATETIME        NOT NULL,
    [OPIDSTXT] NVARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_METLOPI] PRIMARY KEY CLUSTERED ([OPICDCOD] ASC) WITH (FILLFACTOR = 90)
);

