CREATE TABLE [dbo].[SEFases] (
    [NRO]       SMALLINT      NOT NULL,
    [FASENRO]   SMALLINT      NOT NULL,
    [TITULO]    TEXT          NULL,
    [LINK]      TEXT          NULL,
    [FECHAALTA] SMALLDATETIME NULL,
    [FECHACAD]  SMALLDATETIME NULL,
    CONSTRAINT [PK_SEFases] PRIMARY KEY CLUSTERED ([NRO] ASC, [FASENRO] ASC) WITH (FILLFACTOR = 90)
);

