CREATE TABLE [dbo].[SLTLRME] (
    [RMEINLTR] INT           NOT NULL,
    [RMEDSNIF] CHAR (21)     NULL,
    [RMESTNOM] VARCHAR (50)  NOT NULL,
    [RMESTCO1] VARCHAR (50)  NOT NULL,
    [RMESTCO2] VARCHAR (50)  NULL,
    [RMESTLLT] VARCHAR (150) NOT NULL,
    [RMESTARE] VARCHAR (150) NOT NULL,
    [RMESTEDI] VARCHAR (150) NOT NULL,
    [RMESTCOR] VARCHAR (100) NOT NULL,
    [RMESTTEL] VARCHAR (25)  NULL,
    [RMWNREN]  CHAR (1)      CONSTRAINT [DF_SLTLRME_RMWNREN] DEFAULT ('N') NULL,
    [RMEDSTOR] CHAR (25)     NULL,
    CONSTRAINT [PK_SLTLRME] PRIMARY KEY CLUSTERED ([RMEINLTR] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SLTLRME_METLLTR] FOREIGN KEY ([RMEINLTR]) REFERENCES [dbo].[METLLTR] ([LTRINCOD]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_SLTLRME_7_1567396703__K2_K1]
    ON [dbo].[SLTLRME]([RMEDSNIF] ASC, [RMEINLTR] ASC);


GO
CREATE STATISTICS [_dta_stat_1567396703_1_2]
    ON [dbo].[SLTLRME]([RMEINLTR], [RMEDSNIF]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Renuncio al examen?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SLTLRME', @level2type = N'COLUMN', @level2name = N'RMWNREN';

