CREATE TABLE [dbo].[SOLTLBVE] (
    [BVEINCOD] INT           NOT NULL,
    [BVESTNIF] VARCHAR (9)   NOT NULL,
    [BVESTNOM] VARCHAR (100) NOT NULL,
    [BVESTCOG] VARCHAR (200) NOT NULL,
    [BVESTTEL] VARCHAR (9)   NULL,
    [BVESTCOR] VARCHAR (200) NULL,
    [BVESTMAT] VARCHAR (10)  NOT NULL,
    [BVESTMOT] TEXT          NOT NULL,
    [BVEDTBAI] DATETIME      NOT NULL,
    [BVEDTSOL] DATETIME      CONSTRAINT [DF__SOLTLBVE__BVEDTS__6C5905DD] DEFAULT (getdate()) NOT NULL,
    [BVEBOTRA] CHAR (1)      CONSTRAINT [DF__SOLTLBVE__BVEBOT__6D4D2A16] DEFAULT ('N') NULL,
    CONSTRAINT [PK__SOLTLBVE__6B64E1A4] PRIMARY KEY CLUSTERED ([BVEINCOD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__SOLTLBVE__BVEINC__6E414E4F] FOREIGN KEY ([BVEINCOD]) REFERENCES [dbo].[METLLTR] ([LTRINCOD]) ON DELETE CASCADE
);

