CREATE TABLE [dbo].[SOLTLCDF] (
    [CDFINCOD] INT           NOT NULL,
    [CDFSTNIF] CHAR (21)     NOT NULL,
    [CDFSTNOM] VARCHAR (100) NOT NULL,
    [CDFSTCOG] VARCHAR (150) NOT NULL,
    [CDFSTCOR] VARCHAR (255) NOT NULL,
    [CDFSTTVI] VARCHAR (50)  NULL,
    [CDFSTVIA] VARCHAR (100) NULL,
    [CDFSTVIL] VARCHAR (50)  NULL,
    [CDFSTNUM] CHAR (4)      CONSTRAINT [DF_SOLTLCDF_CDFSTNUM] DEFAULT (0) NOT NULL,
    [CDFSTBIS] CHAR (2)      NOT NULL,
    [CDFINESC] CHAR (4)      NOT NULL,
    [CDFINPIS] CHAR (4)      NOT NULL,
    [CDFINPOR] CHAR (4)      NOT NULL,
    [CDFSTCPO] INT           NOT NULL,
    [CDFSTMUN] VARCHAR (500) NOT NULL,
    [CDFSTPRO] VARCHAR (500) NOT NULL,
    [CDFSTPAI] VARCHAR (50)  NOT NULL,
    [CDFDTSOL] DATETIME      CONSTRAINT [DF_SOLTLCDF_CDFDTSOL] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_SOLTLCDF] PRIMARY KEY CLUSTERED ([CDFINCOD] ASC) WITH (FILLFACTOR = 90)
);

