CREATE TABLE [dbo].[TRTLFHO] (
    [FCOINPER] INT           NOT NULL,
    [FCOTPFCO] NCHAR (2)     NOT NULL,
    [FCOWNFCO] SMALLINT      NOT NULL,
    [FCOTPREA] NCHAR (1)     NOT NULL,
    [FCOWNANY] SMALLINT      NOT NULL,
    [FCOCDEAF] INT           NOT NULL,
    [FCOTPTEM] NCHAR (3)     NOT NULL,
    [FCOWNDUR] INT           NOT NULL,
    [FCOINCEN] INT           NOT NULL,
    [FCODTINI] INT           NOT NULL,
    [FCODTFIN] INT           NOT NULL,
    [FCOTPESP] NCHAR (2)     NOT NULL,
    [FCODSCOM] NVARCHAR (60) NOT NULL,
    [FCOSWASL] NCHAR (1)     NOT NULL,
    [FCOWNCON] INT           NOT NULL
);

