CREATE TABLE [dbo].[TRTLPER] (
    [PERINPER]           INT             NOT NULL,
    [PERCDNIF]           CHAR (20)       NOT NULL,
    [PERSWNIF]           CHAR (1)        NOT NULL,
    [PERCDPED]           CHAR (3)        NOT NULL,
    [PERDSCO1]           CHAR (25)       NOT NULL,
    [PERDSCO2]           CHAR (25)       NOT NULL,
    [PERDSNOM]           CHAR (20)       NOT NULL,
    [PERDSCO1_M]         CHAR (25)       NOT NULL,
    [PERDSCO2_M]         CHAR (25)       NOT NULL,
    [PERDSNOM_M]         CHAR (20)       NOT NULL,
    [PERTPCAR]           CHAR (2)        NOT NULL,
    [PERWNNUM]           CHAR (7)        NOT NULL,
    [PERDSBIS]           CHAR (1)        NOT NULL,
    [PERDSESC]           CHAR (2)        NOT NULL,
    [PERDSPIS]           CHAR (3)        NOT NULL,
    [PERDSPOR]           CHAR (4)        NOT NULL,
    [PERINPPM]           CHAR (12)       NOT NULL,
    [PERTPPPM]           CHAR (2)        NOT NULL,
    [PERCDPOS]           CHAR (5)        NOT NULL,
    [PERWNTE1]           CHAR (20)       NOT NULL,
    [PERWNTE2]           CHAR (20)       NOT NULL,
    [PERWNTE3]           CHAR (20)       NOT NULL,
    [PERDTNAI]           INT             NOT NULL,
    [PERDTNAI_DT]        DATETIME        NULL,
    [PERDTNAI_EDAT]      SMALLINT        NOT NULL,
    [PERINPPN]           CHAR (12)       NOT NULL,
    [PERTPPPN]           CHAR (2)        NOT NULL,
    [PERSWSEX]           SMALLINT        NOT NULL,
    [PERSWSEX_DS]        VARCHAR (60)    NOT NULL,
    [PERSWECI]           SMALLINT        NOT NULL,
    [PERSWECI_DS]        VARCHAR (60)    NOT NULL,
    [PERSWDIS]           CHAR (1)        NOT NULL,
    [PERSWCDI]           CHAR (1)        NOT NULL,
    [PERSWCMR]           CHAR (1)        NOT NULL,
    [PERSWCDD]           CHAR (1)        NOT NULL,
    [PERDSC1C]           CHAR (25)       NOT NULL,
    [PERDSC2C]           CHAR (25)       NOT NULL,
    [PERDSNOC]           CHAR (20)       NOT NULL,
    [PERDTNAC]           INT             NOT NULL,
    [PERDTNAC_DT]        DATETIME        NULL,
    [PERSWDIC]           CHAR (1)        NOT NULL,
    [PERSWTRC]           CHAR (1)        NOT NULL,
    [PERSWTAC]           CHAR (1)        NOT NULL,
    [PERDSORC]           CHAR (20)       NOT NULL,
    [PERCDEMP]           SMALLINT        NOT NULL,
    [PERWNEMP]           SMALLINT        NOT NULL,
    [PERCDTRA]           SMALLINT        NOT NULL,
    [PERCDTRP]           SMALLINT        NOT NULL,
    [PERCDTRP_DS]        VARCHAR (40)    NOT NULL,
    [PERCDFIT]           CHAR (8)        NOT NULL,
    [PERCDFIT_DSTRE]     VARCHAR (60)    NOT NULL,
    [PERCDFIT_DSCAT]     VARCHAR (60)    NOT NULL,
    [PERCDPSN]           INT             NOT NULL,
    [PERWNUNI]           SMALLINT        NOT NULL,
    [PERDSASS]           CHAR (12)       NOT NULL,
    [PERDTASS]           INT             NOT NULL,
    [PERDTING]           INT             NOT NULL,
    [PERDTANT]           INT             NOT NULL,
    [PERDTVTR]           INT             NOT NULL,
    [PERDTBAI]           INT             NOT NULL,
    [PERDTPPO]           INT             NOT NULL,
    [PERCDMAT]           INT             NOT NULL,
    [PERSWRLA]           SMALLINT        NOT NULL,
    [PERSWRLA_DS]        VARCHAR (60)    NOT NULL,
    [PERSWRGE]           CHAR (1)        NOT NULL,
    [PERDTRGE]           INT             NOT NULL,
    [PERSWRGI]           CHAR (1)        NOT NULL,
    [PERDTRGI]           INT             NOT NULL,
    [PERSWGGU]           CHAR (1)        NOT NULL,
    [PERWNAPL]           INT             NOT NULL,
    [PERDTAPL]           INT             NOT NULL,
    [PERSWACN]           CHAR (1)        NOT NULL,
    [PERSWREC]           CHAR (1)        NOT NULL,
    [PERTPCON]           SMALLINT        NOT NULL,
    [PERCDPAR]           CHAR (5)        NOT NULL,
    [PERCDHOR]           DECIMAL (7, 2)  NOT NULL,
    [PERCDGPR]           CHAR (2)        NOT NULL,
    [PERCDGRE]           CHAR (3)        NOT NULL,
    [PERCDNCD]           SMALLINT        NOT NULL,
    [PERWNIRP]           DECIMAL (5, 2)  NOT NULL,
    [PERWNIRA]           DECIMAL (5, 2)  NOT NULL,
    [PERWNNFR]           SMALLINT        NOT NULL,
    [PERWNTRI]           SMALLINT        NOT NULL,
    [PERWNTRV]           SMALLINT        NOT NULL,
    [PERCDJEF]           SMALLINT        NOT NULL,
    [PERWNDIT]           SMALLINT        NOT NULL,
    [PERCDEPI]           SMALLINT        NOT NULL,
    [PERWNCSS]           SMALLINT        NOT NULL,
    [PERDTIBR]           INT             NOT NULL,
    [PERDTISU]           INT             NOT NULL,
    [PERDTIBO]           INT             NOT NULL,
    [PERDTIRE]           INT             NOT NULL,
    [PERDTIMA]           INT             NOT NULL,
    [PERWNDCO]           SMALLINT        NOT NULL,
    [PERWNHCO]           SMALLINT        NOT NULL,
    [PERWNGRC]           SMALLINT        NOT NULL,
    [PERWNDIC]           SMALLINT        NOT NULL,
    [PERWNE00]           SMALLINT        NOT NULL,
    [PERWNE60]           SMALLINT        NOT NULL,
    [PERWNE75]           SMALLINT        NOT NULL,
    [PERWNACC]           SMALLINT        NOT NULL,
    [PERWN126]           SMALLINT        NOT NULL,
    [PERWNI00]           SMALLINT        NOT NULL,
    [PERWNI60]           SMALLINT        NOT NULL,
    [PERWNI75]           SMALLINT        NOT NULL,
    [PERWNIAC]           SMALLINT        NOT NULL,
    [PERWNCMI]           SMALLINT        NOT NULL,
    [PERWNPSS]           SMALLINT        NOT NULL,
    [PERWNA71]           SMALLINT        NOT NULL,
    [PERWNMAT]           SMALLINT        NOT NULL,
    [PERCDCC2]           SMALLINT        NOT NULL,
    [PERCDCTC]           SMALLINT        NOT NULL,
    [PERXCBCC]           DECIMAL (11, 2) NOT NULL,
    [PERXCBCP]           DECIMAL (11, 2) NOT NULL,
    [PERXCBC2]           DECIMAL (11, 2) NOT NULL,
    [PERXCBP2]           DECIMAL (11, 2) NOT NULL,
    [PERSWBAC]           CHAR (1)        NOT NULL,
    [PERXTISU]           DECIMAL (11, 2) NOT NULL,
    [PERWNDCM]           SMALLINT        NOT NULL,
    [PERSWVAG]           CHAR (1)        NOT NULL,
    [PERSWREJ]           CHAR (1)        NOT NULL,
    [PERWNCTP]           DECIMAL (4, 3)  NOT NULL,
    [PERCDBNC]           CHAR (4)        NOT NULL,
    [PERCDSUC]           CHAR (4)        NOT NULL,
    [PERWNDIG]           CHAR (2)        NOT NULL,
    [PERWNCOM]           CHAR (10)       NOT NULL,
    [PERCDUSA]           CHAR (8)        NOT NULL,
    [PERDTUSA]           INT             NOT NULL,
    [PERCDUSB]           CHAR (8)        NOT NULL,
    [PERDTUSB]           INT             NOT NULL,
    [PERCDUSM]           CHAR (8)        NOT NULL,
    [PERDTUSM]           INT             NOT NULL,
    [PERDHMOD]           CHAR (22)       NOT NULL,
    [PERCDORD]           CHAR (30)       NOT NULL,
    [PERCDSLI]           SMALLINT        NOT NULL,
    [PERTPCOI]           SMALLINT        NOT NULL,
    [PERCDDIS]           SMALLINT        NOT NULL,
    [PERCDDIS_DS]        VARCHAR (60)    NOT NULL,
    [PERCDSFA]           SMALLINT        NOT NULL,
    [PERCDNIC]           CHAR (20)       NOT NULL,
    [PERXTPCO]           DECIMAL (11, 2) NOT NULL,
    [PERXTAFI]           DECIMAL (11, 2) NOT NULL,
    [PERDTIEX]           INT             NOT NULL,
    [PERDTFEX]           INT             NOT NULL,
    [PERSWACP]           CHAR (1)        NOT NULL,
    [PERCDFUN]           CHAR (5)        NOT NULL,
    [PERCDEDI]           INT             NOT NULL,
    [PERCDEDI_NOM]       VARCHAR (40)    NOT NULL,
    [PERCDEDI_TIPUS_VIA] VARCHAR (15)    NOT NULL,
    [PERCDEDI_NOM_VIA]   VARCHAR (50)    NOT NULL,
    [PERCDEDI_NUMERO]    SMALLINT        NOT NULL,
    [PERCDEDI_BIS]       CHAR (1)        NOT NULL,
    [PERCDEDI_CP]        SMALLINT        NOT NULL,
    [PERCDPLA]           CHAR (3)        NOT NULL,
    [PERCDTEF]           CHAR (20)       NOT NULL,
    [PERSWEPP]           CHAR (1)        NOT NULL,
    [PERCDTPP]           SMALLINT        NOT NULL,
    [PERCDTPP_DS]        VARCHAR (60)    NOT NULL,
    [PERDTAPP]           INT             NOT NULL,
    [PERDTAPP_DT]        DATETIME        NULL,
    [PERDTIAP]           INT             NOT NULL,
    [PERDTIAP_DT]        DATETIME        NULL,
    [PERCDBPP]           CHAR (4)        NOT NULL,
    [PERCDSPP]           CHAR (4)        NOT NULL,
    [PERWNDPP]           CHAR (2)        NOT NULL,
    [PERWNCPP]           CHAR (10)       NOT NULL,
    [PERDSCAR]           VARCHAR (50)    NOT NULL,
    [PERDSEPL]           VARCHAR (50)    NOT NULL,
    [PERDSNOT]           VARCHAR (254)   NOT NULL,
    [PERDSEML]           VARCHAR (254)   NOT NULL,
    [PERSWUPR]           CHAR (1)        NOT NULL,
    [PERSWPAL]           CHAR (1)        NOT NULL,
    [PERDSUSU]           VARCHAR (254)   NOT NULL,
    [PERSWINO]           CHAR (1)        NOT NULL,
    [PERSWICR]           CHAR (1)        NOT NULL,
    [PERDTUCI]           DATETIME        NULL
);

