CREATE TABLE [dbo].[TTTLPRO] (
    [PROINCOD] INT           IDENTITY (1, 1) NOT NULL,
    [PRODSNOM] VARCHAR (50)  NULL,
    [PRODSDES] VARCHAR (500) NULL,
    [PROINVIS] INT           NULL,
    CONSTRAINT [PK_TTTLPRO] PRIMARY KEY CLUSTERED ([PROINCOD] ASC) WITH (FILLFACTOR = 90)
);

