CREATE TABLE [dbo].[TTTLCAT] (
    [CATINCOD] INT           IDENTITY (1, 1) NOT NULL,
    [CATDSNOM] VARCHAR (50)  NULL,
    [CATDSDES] VARCHAR (500) NULL,
    [CATINPRO] INT           NULL,
    [CATINVIS] INT           NULL,
    CONSTRAINT [PK_TTTLCAT] PRIMARY KEY CLUSTERED ([CATINCOD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TTTLCAT_TTTLPRO] FOREIGN KEY ([CATINPRO]) REFERENCES [dbo].[TTTLPRO] ([PROINCOD]) ON UPDATE CASCADE
);

