CREATE TABLE [dbo].[TTTLUSC] (
    [USCINUSU] INT NOT NULL,
    [USCINCAT] INT NOT NULL,
    [USCINACT] INT NULL,
    CONSTRAINT [PK_TTTLUSC] PRIMARY KEY CLUSTERED ([USCINUSU] ASC, [USCINCAT] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TTTLUSC_TTTLCAT] FOREIGN KEY ([USCINCAT]) REFERENCES [dbo].[TTTLCAT] ([CATINCOD]) ON UPDATE CASCADE,
    CONSTRAINT [FK_TTTLUSC_TTTLUSU] FOREIGN KEY ([USCINUSU]) REFERENCES [dbo].[TTTLUSU] ([USUINCOD]) ON UPDATE CASCADE
);

