CREATE FUNCTION anyAnterior (@codi int, @desde as datetime, @fins as datetime)
RETURNS table AS RETURN

    SELECT TOP 1 COUNT(*) AS RECOMPTE 
	FROM METLLTR M LEFT JOIN CSTLCOD C ON C.CODTPCOD = 'TT' 
	AND C.CODWNCOD=M.LTRCDTRA LEFT JOIN METLATR M2 ON M2.ATRCDLTR=M.LTRINCOD 
	AND M2.ATRINCOD = (SELECT TOP 1 M_AUX.ATRINCOD FROM METLATR M_AUX WHERE M_AUX.ATRCDLTR = M.LTRINCOD ORDER BY ATRTPFEC DESC)
	WHERE C.CODDSTIP='W' AND M.LTRDTFEC >  @desde AND M.LTRDTFEC <= @fins AND C.CODWNCOD=@codi
GROUP BY C.CODWNCOD 
