<%
    'Tipus camp
    lh_Desconegut = 0
    lhArray = 1
    lhBigInt = 2
    lhBinary = 3
    lhBoolean = 4
    lhBSTR = 5
    lhChapter = 6
    lhChar = 7
    lhCurrency = 8
    lhDate = 9
    lhDBDate = 10
    lhDBTime = 11
    lhDBTimeStamp = 12
    lhDecimal = 13
    lhDouble = 14
    lhEmpty = 15
    lhErrorDB = 16
    lhFileTime = 17
    lhGUID = 18
    lhIDispatch = 19
    lhInteger = 20
    lhIUnknown = 21
    lhLongVarBinary = 22
    lhLongVarChar = 23
    lhLongVarWChar = 24
    lhNumeric = 25
    lhPropVariant = 26
    lhSingle = 27
    lhSmallInt = 28
    lhTinyInt = 29
    lhUnsignedBigInt = 30
    lhUnsignedInt = 31
    lhUnsignedSmallInt = 32
    lhUnsignedTinyInt = 33
    lhUserDefined = 34
    lhVarBinary = 35
    lhVarChar = 36
    lhVariant = 37
    lhVarNumeric = 38
    lhVarWChar = 39
    lhWChar = 40


    'Tipus error
    lh_ErrorDesconegut = 0
    lhNoError = 1
    lhSistema = 2
    lhSQL = 3


    'Estat connexió
    lh_Desconegut = 0
    lhNoCreada = 1
    lhOberta = 2
    lhTancada = 3
%>