<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center">

<table width="760" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding-top:10px" align="left">	
			<table width="100%" border="0" cellspacing="0" cellpadding="0">        
				<tr> 
					<td colspan="5">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							 <tr> 
								<td width="17" height="17"><img src="/img/common/vorera_esq.png" style="border:0"/></td>
								<td colspan="2" height="17" valign="top"><table style="border-top:1px solid #c4c4c4;" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td></td></tr></table></td>
								<td width="17" height="17"><img src="/img/common/vorera_dre.png" style="border:0"/></td>
							</tr> 
						</table>
					</td>
				</tr>        
				<tr> 
					<td width="1" bgcolor="#c4c4c4"></td>
					<td align="left" style="padding-left:10px"><a href="/home.aspx"><img src="/img/common/logo_hospinet.png" class="border0"/></a></td>
					<td align="center" valign="top">&nbsp;</td>
					<td align="right"><img src="/img/common/fasana_ajuntament.png" style="border:0"/></td>
					<td width="1" bgcolor="#c4c4c4"></td> 
				</tr>				
        <tr> 
          <td colspan="5" background="/img/common/fons_barra.png">		
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td align="left">					
									<table border="0" cellspacing="3" cellpadding="0" width="100%">
										<td valign="middle" align="left" class="paddingDreta10"><img src="/img/common/icona_ajuntament.png" class="valignMiddle border0"/></td>
										<td align="center" nowrap><a href="/home.asp" class="blanc t08 RobotoCondensed valignMiddle nodeco">INICI</a></td>
										<td align="center" class="paddingDretaEsquerra5"><img src="/img/common/separador_linea_blanca.png" ></td>
										<td align="center" nowrap><a href="http://www.l-h.cat/" class="blanc t08 RobotoCondensed nodeco" target="_blank">AJUNTAMENT ON-LINE</a></td>
										<td align="center" class="paddingDretaEsquerra5"><img src="/img/common/separador_linea_blanca.png"></td>
										<td align="center" nowrap><a href="/html/cgis/Llistitelefonic/Listintelefonico.aspx" class="blanc t08 RobotoCondensed valignMiddle nodeco"><img src="/img/common/ico_llisti.png" class="marginDreta5 border0 valignMiddle">LLIST&Iacute; TELEF&Ograve;NIC</a></td>                       
										<td align="center" class="paddingDretaEsquerra5"><img src="/img/common/separador_linea_blanca.png"></td>
										<td align="center" nowrap><a href="http://www.l-h.cat/recullpremsa" class="blanc t08 RobotoCondensed valignMiddle nodeco" target="_blank"><img src="/img/common/ico_recull.png" class="marginDreta5 border0 valignMiddle">RECULL DE PREMSA</a></td> 
										<td valign="middle" align="center" nowrap width="35%"><form class="margin0 padding0" name="busqueda" action="/utils/cercador/cercador.aspx" method="post"><input type="text" class="border0 padding4 arial valignMiddle t075 marginDreta5" name="txtCercaCapcalera" id="txtCercaCapcalera"/><input id="Cercar" name="Cercar" class="border0 valignMiddle" type="image" src="/img/common/lupa.png"  onclick="document.busqueda.submit()" onkeypress="document.busqueda.submit()"/></form></td> 
										<td align="right" nowrap class="paddingDreta10"><img src="/img/common/ico_espaipersonal.png" style="vertical-align:middle;">&nbsp;<a href="/asp/areapersonal.aspx" class="arial blanc t07 nodeco">Espai personal</a></td>
										<td align="right" nowrap><% IF Session("login") THEN
									Response.write("<a href=""/asp/areapersonal.aspx?desconectar=1"" class=""nodeco valignMiddle""><img src=""/img/common/ico_desconnectar.png"" class=""border0""></a>")
									END IF%></td>     
								</table>								
								</td>					
							</tr>
						</table>         
				
					</td>
        </tr>
      </table>    
    </td>
	</tr>
	<tr>
		<td valign="top" align="left">
  
     
