		</td>
	</tr>
	<tr>
		<td valign="top"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
        <tr> 
          <td width="16" height="21"><img src="/img/common/vorera_peu_esq.png"></td>
          <td background="/img/common/fons_barra.png">&nbsp;</td>
          <td width="16" height="21"><img src="/img/common/vorera_peu_dre.png"></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="3" align="center">
        <tr> 
          <td width="20"></td>
          <td class="gris t07 arial">&copy; Copyright 2008 Ajuntament de L'Hospitalet.</td>        
        </tr>
      </table>
    </td>
  </tr>  
</table>

</td>
</tr>
</table>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-156874-14']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

