'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class visorArbresLite

    '''<summary>
    '''lblDebug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebug As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''arbreTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arbreTreeView As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''actualitzaNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actualitzaNode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''actualitzaNodeArbre2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actualitzaNodeArbre2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idioma As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''llistaArbres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents llistaArbres As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RadTree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTree1 As Global.Telerik.WebControls.RadTreeView

    '''<summary>
    '''RetornarNodes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RetornarNodes2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''labelNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelNodes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labelNroNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelNroNodes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''retornarNodesChecked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents retornarNodesChecked As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cerca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadTree2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTree2 As Global.Telerik.WebControls.RadTreeView

    '''<summary>
    '''tipusNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipusNode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''noddstxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noddstxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''llistaArbres2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents llistaArbres2_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''llistaArbres2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents llistaArbres2_2 As Global.System.Web.UI.WebControls.DropDownList
End Class
